/**
 * GENERADO por scripts/gen-mapa-rutas.js. NO editar a mano.
 *
 * El mapa de rutas de la app. Lo consume el audit visual (Maestro) y, sobre
 * todo, ARGOS: para poder llevar al usuario a una pantalla necesita saber
 * qué pantallas existen.
 *
 * Regenerar:  node scripts/gen-mapa-rutas.js
 */
export const APP_SCHEME = "atp";

/** Rutas sin parámetros: se pueden abrir tal cual. */
export const APP_ROUTES: readonly string[] = [
  "/",
  "/afiliados/aplicar",
  "/afiliados/dashboard",
  "/afiliados/mi-codigo",
  "/agenda",
  "/argos",
  "/argos-chat",
  "/argos-recipes",
  "/argos/conversations",
  "/argos/meet",
  "/atp-orden",
  "/biblioteca",
  "/braverman",
  "/braverman-premium",
  "/breathing",
  "/builder",
  "/cardio-import",
  "/centro",
  "/checkin",
  "/clinical-system",
  "/cocina",
  "/comunidad/amigos",
  "/comunidad/animo",
  "/comunidad/buscar",
  "/comunidad/ranking",
  "/cycle",
  "/cycle-charts",
  "/cycle-history",
  "/cycle-settings",
  "/dev",
  "/dev/goal-tree-smoke",
  "/economy/admin",
  "/economy/convert",
  "/economy/history",
  "/economy/how-to-earn",
  "/economy/shop",
  "/edad-atp",
  "/edad-atp/biomarkers",
  "/edad-atp/cinematic-tests-index",
  "/edad-atp/cognitive",
  "/edad-atp/composition",
  "/edad-atp/lab-confirmation",
  "/edad-atp/labs",
  "/edad-atp/questionnaires",
  "/edad-atp/questionnaires/cardiovascular",
  "/edad-atp/questionnaires/habitos",
  "/edad-atp/questionnaires/inflamacion",
  "/edad-atp/questionnaires/inmunidad",
  "/edad-atp/questionnaires/metabolismo",
  "/edad-atp/questionnaires/renal-micronutrientes",
  "/edad-atp/questionnaires/sistema-hormonal",
  "/edad-atp/questionnaires/sueno",
  "/edad-atp/questionnaires/vitalidad",
  "/edad-atp/result-preview",
  "/edad-atp/test-bolt",
  "/edad-atp/test-old-man",
  "/edad-atp/test-plank",
  "/edad-atp/test-recovery-hr",
  "/edad-atp/tests",
  "/edad-atp/tests/balance",
  "/edad-atp/tests/chronotype",
  "/edad-atp/tests/cooper",
  "/edad-atp/tests/push-ups",
  "/edad-atp/tests/reaction-time",
  "/edad-atp/vitals",
  "/emotion-exploration",
  "/emotion-history",
  "/emotion-navigation",
  "/emotion-profile",
  "/emotions",
  "/execution",
  "/exercise-detail",
  "/exercise-library",
  "/fasting",
  "/feedback-dashboard",
  "/ficha-emergencia",
  "/fitness-cardio",
  "/fitness-hiit",
  "/fitness-hub",
  "/fitness-my",
  "/fitness-strength",
  "/fitness-train",
  "/food-barcode",
  "/food-log",
  "/food-preferences",
  "/food-register",
  "/food-scan",
  "/food-text",
  "/forgot-password",
  "/functional-quiz",
  "/glucose-log",
  "/health-hub",
  "/health-input",
  "/historia-clinica",
  "/history",
  "/hoy-habitos",
  "/hydration",
  "/journal",
  "/journal-history",
  "/ketones-log",
  "/kit",
  "/labs-guide",
  "/legal/aviso",
  "/legal/terminos",
  "/lista-compra",
  "/log-cardio",
  "/log-exercise",
  "/log-strength",
  "/login",
  "/medidas",
  "/meditation",
  "/mente/nback",
  "/mente/nback/como-jugar",
  "/mente/nback/personalizar",
  "/mente/nback/saber-mas",
  "/mente/nback/sesion",
  "/mente/nback/stats",
  "/mente/player",
  "/mente/progreso",
  "/mobility-assessment",
  "/my-chronotype",
  "/my-health",
  "/my-recipes",
  "/my-routines",
  "/night-filter",
  "/notifications",
  "/nutrition",
  "/onboarding/v2/chronotype",
  "/onboarding/v2/consent",
  "/onboarding/v2/cycle",
  "/onboarding/v2/goal",
  "/onboarding/v2/notifications",
  "/onboarding/v2/positioning",
  "/onboarding/v2/privacy",
  "/onboarding/v2/profile",
  "/onboarding/v2/welcome",
  "/onboarding/voice-config",
  "/ordenar-dia",
  "/packs/armar",
  "/paywall",
  "/perfil",
  "/plan-entrenamiento",
  "/profile",
  "/progreso",
  "/progress",
  "/protocol-explorer",
  "/quiz-take",
  "/quiz/chronotype",
  "/quizzes",
  "/redeem-code",
  "/register",
  "/reports",
  "/reset-password",
  "/routine-generator",
  "/salud",
  "/salud/cuestionario-maestro",
  "/salud/diagnostico",
  "/salud/evolucion",
  "/salud/expediente",
  "/salud/ficha-emergencia",
  "/salud/hoy",
  "/salud/intervenciones",
  "/salud/intervenciones/rationale",
  "/salud/mi-expediente",
  "/salud/mis-datos",
  "/salud/mis-evaluaciones",
  "/salud/mis-sintomas",
  "/salud/padecimientos",
  "/salud/sintomas",
  "/session",
  "/settings",
  "/settings/comunidad",
  "/settings/conexiones",
  "/settings/cuenta",
  "/settings/dev",
  "/settings/experiencia",
  "/settings/legal",
  "/settings/notifications",
  "/settings/privacy",
  "/settings/salud",
  "/settings/subscription",
  "/shared-routine",
  "/sleep",
  "/sleep-session",
  "/solar",
  "/strength-session",
  "/supplements",
  "/tests",
  "/tests/resultado/cronotipo",
  "/tribu",
];

/** Rutas que necesitan un parámetro. ARGOS debe resolverlo antes de navegar. */
export const APP_ROUTES_DYNAMIC: readonly string[] = [
  "/centro/[appKey]",
  "/comunidad/perfil/[userId]",
  "/edad-atp/sub-edad/[key]",
  "/historia-clinica/[category]",
  "/packs/[packKey]",
  "/reports/[dominio]",
  "/salud/intervenciones/[key]",
  "/tests/q/[id]",
  "/tests/run/[id]",
];

/**
 * Qué hace cada pantalla, cosechado del encabezado de su propio archivo.
 *
 * Es la semilla del conocimiento que ARGOS necesita para EXPLICAR la app, no
 * solo para navegarla. Viene del código, así que no se desactualiza sola; lo
 * que salga pobre se mejora editando el docblock de la pantalla, que es donde
 * debe vivir.
 *
 * 🚨 NO SE LE ENTREGA CRUDO AL USUARIO. Estos textos están escritos por y para
 * desarrollo: traen números de migración, claves de sprint (MB-32, #47) y
 * nombres propios del equipo. Antes de que ARGOS los use en una respuesta hay
 * que pasarlos por una limpieza de copy. Sirven como CONTEXTO para el modelo,
 * nunca como texto a citar.
 */
export const APP_ROUTE_DESCRIPTIONS: Readonly<Record<string, string>> = {
  "/": "HOY = TAREAS — tu checklist del día. Fin. Nada más. (MB-20 Pieza 1) Usa compileDay() como única fuente de datos. Estructura:",
  "/afiliados/aplicar": "Afiliados — Aplicación (#47 fase 1). Formulario de alta como afiliado (INSERT en affiliates status=pending, backend migración 101 Cowork).",
  "/afiliados/dashboard": "Afiliados — Dashboard (#47 fase 1). Solo afiliados aprobados: wallet, referidos, comisiones, código con copiar/compartir, gráfica de referidos",
  "/afiliados/mi-codigo": "Afiliados — Mi código (#47 fase 1). Código único + preview del landing que verán los invitados (somosatp.com/[codigo] — web, fase posterior) +",
  "/agenda": "/agenda (#v13h — rediseño editorial) — ventana dependiente de HOY: timeline de eventos del día como mini-cards horizontales. Fondo gradient vertical + header editorial (título grande + fecha",
  "/argos": "N1 — ARGOS como tab inferior. Re-exporta la pantalla de chat existente (app/argos-chat.tsx) sin duplicar lógica. La ruta /argos-chat sigue válida para deep links existentes.",
  "/argos-chat": "ARGOS Chat — pantalla orquestadora (MB-21 Pieza 4). Era un archivo de 800 líneas con estilos a mano y hex crudos. Ahora:",
  "/argos-recipes": "Recetas de ARGOS — redirect (OLA3 · Anexo D §1). El generador es parte de la pestaña Recetas de /cocina. Su lista de super en memoria murió: la única puerta receta→lista es sendRecipeToList.",
  "/argos/conversations": "ARGOS — Historial de conversaciones (F2.2 #93 · MB-21 Pieza 3). Lo que lo vuelve usable con cincuenta conversaciones: grupos por fecha",
  "/argos/meet": "Meet ARGOS — primer contacto post-onboarding (T6 MAGIA ARGOS · T1 ONBOARDING épico). Secuencia cinemática de 5 pantallas (Propuesta A, guion en",
  "/atp-orden": "Mi orden (MB-19 PIEZA 2) — la pantalla que edita el orden \"Mío\" de la sala ATP. Con una LISTA, no arrastrando. Subir, bajar y fijar arriba resuelven el 100%",
  "/biblioteca": "Tab vieja Biblioteca — redirect para deep links externos (OLA0 QW-6).",
  "/braverman": "Test de Braverman — Evaluación clínica de neurotransmisores. 313 preguntas V/F divididas en 2 partes (dominancia + deficiencias).",
  "/braverman-premium": "REPORTE PREMIUM ARGOS — Braverman (#90, #143). Doctrina H+: se COBRA con Protones (1,000 H+, precio server-side), NO se",
  "/breathing": "Respiración — Timer con animación de círculo expandible/contractible. Ciclos de inhala/retén/exhala con visualización.",
  "/builder": "Builder — Editor visual de rutinas con bloques anidados. Permite crear y editar rutinas con estructura jerárquica de bloques:",
  "/cardio-import": "Redirect legacy (Ola 2 Fitness PR3, ANEXO_B_FITNESS §5). El import Health es la fase ?fase=importar de /log-cardio",
  "/centro": "El Centro ATP (MB-22 Pieza 2) — el instalador y configurador de apps. Todas las funciones de la app, agrupadas por sección, estilo Ajustes de",
  "/clinical-system": "Drill-down de sistema funcional — Historia Clínica (F3 sprint UX blockers V1.3). Ruta: /clinical-system?system=<FunctionalSystemKey>",
  "/cocina": "/cocina — recetas, lista y preferencias bajo un techo (OLA3 · Anexo D §1). Eran cuatro rutas sueltas (my-recipes, argos-recipes, lista-compra,",
  "/comunidad/amigos": "Comunidad › Amigos (C2) — solicitudes pendientes + lista de amigos. Fuente: list_pending_requests / list_friends / respond_friend_request (184).",
  "/comunidad/animo": "Comunidad › Ánimo de tu gente (MB-4 · Bloque 4). Acompañamiento, no competencia: cada card es alguien que ELIGIÓ compartir",
  "/comunidad/buscar": "Comunidad › Buscar personas (C2) — búsqueda con debounce + agregar amigos. Espejo del servidor: mínimo 2 caracteres y rate limit 20/60s (search_users v2,",
  "/comunidad/ranking": "Comunidad › Ranking (C4) — leaderboard top 20 + tu posición destacada. Copy \"Comunidad, no competencia\": el ranking celebra la constancia, no compite",
  "/cycle": "Ciclo Menstrual — Hub principal de tracking. Muestra fase actual, calendario interactivo mensual, modal de registro",
  "/cycle-charts": "Redirect legacy (OLA1 R-3, ANEXO_A_REPORTS §6). Las gráficas del ciclo son hoy la pestaña Gráficas de /reports/ciclo. El",
  "/cycle-history": "Redirect legacy (OLA1 R-3, ANEXO_A_REPORTS §6). El historial de ciclos es hoy la pestaña Ciclos de /reports/ciclo. El guard",
  "/cycle-settings": "Cycle Settings — Configuración del tracking de ciclo.",
  "/dev": "DEV Tools — menú de herramientas internas (Step COACH 7.1/N). Accesible vía router.push('/dev'). Lista las pantallas de validación/debug.",
  "/dev/goal-tree-smoke": "Goal Tree LLM Smoke Test (DEV) — Step COACH 7/N. Pantalla de desarrollo para validar manualmente que GoalTree.decomposeGoal",
  "/economy/admin": "MI PROGRESO — pantalla central de balance + rank + logros (E- + H+ + accesos). Nombre antes \"Mi Economía\" — renombrado 23-jun por Enrique (incluye logros, no solo dinero).",
  "/economy/convert": "Convertir E- → H+. Sin slider (no hay dep): stepper de presets (múltiplos de 100) + Máx. Preview en vivo (previewProtons × multiplier de reto). Confirma vía RPC convert.",
  "/economy/history": "Historial de movimientos — filtro E- / H+. Lista las transacciones del usuario.",
  "/economy/how-to-earn": "CÓMO GANAR H+ (#99, marathon F2) — explica visualmente la economía: Electrones (esfuerzo verificado, rank permanente) → conversión →",
  "/economy/shop": "TIENDA H+ — galería editorial (#101, marathon F6). Rediseño del \"callejón trasero de antro\" → piezas de galería: B/N",
  "/edad-atp": "Edad ATP — Hub de captura de datos (Sprint 2, MVP manual). MB-11 D.4: entrada del módulo al molde editorial — hero con imagen",
  "/edad-atp/biomarkers": "Edad ATP — biomarcadores. MEGA COMPLETION (auto-prepopulation). NO muestra una forma vacía: separa \"✓ Disponibles\" (ya en tu expediente,",
  "/edad-atp/cinematic-tests-index": "Redirect legacy (Ola 4, Anexo C, pieza 5). El indice de pruebas cinematicas listaba los fisicos. Lo absorbio el hub unico /tests, que lee",
  "/edad-atp/cognitive": "Placeholder de captura manual retirado — el test vivo es el interactivo (OLA0 QW-6).",
  "/edad-atp/composition": "Edad ATP — composición corporal. Sprint 2.5 (integración). Pre-puebla desde health_measurements (tabla canónica) y guarda ahí mismo —",
  "/edad-atp/lab-confirmation": "Capa 4 del parser v2 — pantalla de confirmación pre-guardado. Tras extraer (sin guardar), el usuario VE todos los valores detectados con su estado",
  "/edad-atp/labs": "ATP Labs — vista CANÓNICA de laboratorios (fuente de verdad `lab_values`). Lista los parámetros con su último valor, agrupados por categoría de la matriz (#13), con filtros",
  "/edad-atp/questionnaires": "Redirect legacy (Ola 4, Anexo C, pieza 5). El indice de cuestionarios de Edad ATP listaba los 9 por dominio. Lo absorbio el hub unico /tests, que lee",
  "/edad-atp/questionnaires/cardiovascular": "Cuestionario Cardiovascular. Copy MVP — // TODO Mariana Sprint 5: validar.",
  "/edad-atp/questionnaires/habitos": "Cuestionario Hábitos. Copy MVP — // TODO Mariana Sprint 5: validar.",
  "/edad-atp/questionnaires/inflamacion": "Cuestionario Inflamación. Copy MVP — // TODO Mariana Sprint 5: validar.",
  "/edad-atp/questionnaires/inmunidad": "Cuestionario Inmunidad. Copy MVP — // TODO Mariana Sprint 5: validar.",
  "/edad-atp/questionnaires/metabolismo": "Cuestionario Metabolismo. Copy MVP — // TODO Mariana Sprint 5: validar.",
  "/edad-atp/questionnaires/renal-micronutrientes": "Cuestionario Renal y micronutrientes. Copy MVP — // TODO Mariana Sprint 5: validar.",
  "/edad-atp/questionnaires/sistema-hormonal": "Cuestionario Sistema hormonal. Copy MVP — // TODO Mariana Sprint 5: validar (incl. preguntas específicas por sexo + fase del ciclo en mujeres).",
  "/edad-atp/questionnaires/sueno": "Cuestionario Sueño. Copy MVP — // TODO Mariana Sprint 5: validar.",
  "/edad-atp/questionnaires/vitalidad": "Cuestionario Vitalidad. Copy MVP — // TODO Mariana Sprint 5: validar.",
  "/edad-atp/result-preview": "Edad ATP — pantalla de resultado. MEGA COMPLETION (Sprint 3 UIUX). Lee TODAS las fuentes vía el orquestador, reproduce la cinemática la primera vez",
  "/edad-atp/test-bolt": "Redirect legacy (Ola 4, Anexo C, pieza 5). El cronometro del BOLT vive en el runner fisico.",
  "/edad-atp/test-old-man": "Redirect legacy (Ola 4, Anexo C, pieza 5). La captura del Old Man Test vive en el runner fisico.",
  "/edad-atp/test-plank": "Redirect legacy (Ola 4, Anexo C, pieza 5). El cronometro del plank vive en el runner fisico.",
  "/edad-atp/test-recovery-hr": "Redirect legacy (Ola 4, Anexo C, pieza 5). La captura de Recovery HR vive en el runner fisico.",
  "/edad-atp/tests": "Redirect legacy (Ola 4, Anexo C, pieza 5). El indice de tests de Edad ATP listaba los mismos fisicos. Lo absorbio el hub unico /tests, que lee",
  "/edad-atp/tests/balance": "Tests funcionales — FORMULARIO de captura (doctrina \"SIMPLE vence inteligente\"): cada test se auto-administra fuera de la app con un reloj/cronómetro de mano y aquí",
  "/edad-atp/tests/chronotype": "Redirect legacy (Ola 4, Anexo C, pieza 5). Alias de Edad ATP. Antes reenviaba a /quiz/chronotype, que ahora tambien es",
  "/edad-atp/tests/cooper": "Redirect legacy (Ola 4, Anexo C, pieza 5). La captura del Cooper vive en el runner fisico.",
  "/edad-atp/tests/push-ups": "Redirect legacy (Ola 4, Anexo C, pieza 5). La captura de push-ups vive en el runner fisico.",
  "/edad-atp/tests/reaction-time": "Test funcional — Cognición (Der & Deary 2006): Simple RT + Choice 4-AFC + Go/No-Go. Mide ms de respuesta (+ tasa de errores en Go/No-Go) y guarda en",
  "/edad-atp/vitals": "Edad ATP — mediciones puntuales (vitals). Sprint 2.5 (integración). Pre-puebla desde health_measurements y guarda ahí mismo (tabla canónica).",
  "/emotion-exploration": "Redirect legacy (OLA5 pieza 1, ANEXO_D §2). Explorar el territorio dejó de ser otra pantalla: es el modo explorar del",
  "/emotion-history": "Redirect legacy (OLA1 R-2, ANEXO_A_REPORTS §6). El historial emocional y el perfil se absorbieron en /reports/emociones, una",
  "/emotion-navigation": "Redirect legacy (OLA5 pieza 2, ANEXO_D §2). Navegar era una ruta hermana a la que solo se llegaba desde el cierre del",
  "/emotion-profile": "Redirect legacy (OLA1 R-2, ANEXO_A_REPORTS §6). El perfil emocional es hoy la pestaña Perfil de /reports/emociones. Se",
  "/emotions": "EMOCIONES — el módulo como módulo (MB-10 · Track H.1). Deja de ser una pantalla suelta colgada de HOY: un solo lugar donde viven",
  "/execution": "Redirect legacy (Ola 2 Fitness PR3, ANEXO_B_FITNESS §5): execution murió. Su interfaz completa vive como TimerModeRunner dentro de /session, que",
  "/exercise-detail": "Exercise Detail — ficha del ejercicio matriceado (MB-3 Track F). Hero con poster + los 11 ejes legibles: músculos, equipo, patrón, dinámica,",
  "/exercise-library": "Exercise Library — biblioteca MATRICEADA (MB-3 Track F · MB-3.5 #9). 214 ejercicios del catálogo exercise_matrix con buscador arriba + filtros por",
  "/fasting": "Ayuno — Rediseño estilo ZERO. 3 estados: IDLE (selector + preview), ACTIVE (ring timer + zonas), HISTORY.",
  "/feedback-dashboard": "Feedback Dashboard — Vista admin para gestionar reportes de testers. Solo accesible por admin (90a55e74-...).",
  "/ficha-emergencia": "/ficha-emergencia — modo pantalla. La ficha para quien te auxilia. OLA6 PIEZA D. Vive en la raíz, fuera de /salud y fuera de cualquier sesión,",
  "/fitness-cardio": "Redirect legacy (Ola 2 Fitness PR3, ANEXO_B_FITNESS §5). El cardio completo vive en /log-cardio (disciplinas, PRs por distancia,",
  "/fitness-hiit": "Redirect legacy (Ola 2 Fitness PR3, ANEXO_B_FITNESS §5). HIIT es la puerta INTERVALOS del generador (presets en",
  "/fitness-hub": "Fitness Hub (MB-3.6 Bloque 1.2) — el hub abre con LA SESIÓN DE HOY. Patrón Oura \"one big thing\": un solo protagonista — qué toca hoy, cuánto",
  "/fitness-my": "Redirect legacy (Ola 2 Fitness PR3, ANEXO_B_FITNESS §5). Mi Fitness se absorbió en /fitness-hub (secciones REGISTRAR / EXPLORAR /",
  "/fitness-strength": "Fuerza (MB-3.6 Bloque 1.1) — FUSIÓN de fitness-strength + personal-records. Antes eran dos pantallas girando sobre el mismo dato (PRs/benchmarks) — un",
  "/fitness-train": "Redirect legacy (Ola 2 Fitness PR3, ANEXO_B_FITNESS §5). Entrenar se absorbió en /fitness-hub (hero del plan, tira de fase y",
  "/food-barcode": "Registro por código de barras — redirect (OLA3 · Anexo D §1). El sensor CÓDIGO vive en /food-log, junto a foto y texto.",
  "/food-log": "/food-log — la captura unificada (OLA3 · Anexo D §1). Un solo eje distinguía a food-text, food-scan y food-barcode: el SENSOR.",
  "/food-preferences": "Preferencias de comida — redirect (OLA3 · Anexo D §1). Es la pestaña Preferencias de /cocina, al lado de su único consumidor: el generador de recetas.",
  "/food-register": "Selección de tipo de comida — redirect (OLA3 · Anexo D §1). Dejó de ser un paso previo: la barra de tipo de comida y la zona de un toque (frecuentes + registros de hoy) son parte de /food-log.",
  "/food-scan": "Escaneo por foto — redirect (OLA3 · Anexo D §1). El sensor FOTO vive en /food-log. mode=label es hoy intent=etiqueta y mode=supplement se mudó a /supplements: la tabla user_supplements tiene un dueño.",
  "/food-text": "Registro por texto — redirect (OLA3 · Anexo D §1). El sensor TEXTO vive en /food-log, junto a foto y código.",
  "/forgot-password": "Pantalla de recuperación de contraseña. Envía un email con enlace de reset vía Supabase Auth.",
  "/functional-quiz": "Redirect legacy (Ola 4, Anexo C, pieza 5). Los 5 cuestionarios funcionales los corre el motor único de /tests/q/[id].",
  "/glucose-log": "Glucose Log — Registro de glucosa en sangre con contexto y rangos visuales. Permite registrar valor mg/dL, contexto (ayuno/pre/post/random/bedtime),",
  "/health-hub": "/health-hub — ya no es pantalla, es un puente. OLA6 PIEZA B: eran 32 líneas que montaban el MISMO cuerpo del tab SALUD, con",
  "/health-input": "Health Input — Formulario de evaluación de salud con secciones colapsables.",
  "/historia-clinica": "Redirect legacy (Ola 4, Anexo C, pieza 5). El indice de historia clinica listaba sus categorias. Lo absorbio el hub unico /tests, que lee",
  "/history": "Historial de Sesiones — Lista cronológica de execution_logs agrupada por fecha, con cards premium por modo (timer/rutina).",
  "/hoy-habitos": "Mis hábitos del HOY (MB-12 · E-3) — la puerta perdida de los electrones. Aquí el usuario decide qué hábitos booleanos y cuantitativos trackea su",
  "/hydration": "Hidratación — Registro de agua con meta diaria, botones rápidos y barra de progreso.",
  "/journal": "Journal — Escritura reflexiva con 4 tipos: Gratitud, Visión, Estoico, Descarga. Selector de tipo + formulario específico + mood tracking + historial.",
  "/journal-history": "Redirect legacy (OLA1 R-1, ANEXO_A_REPORTS §6). El historial del journal se absorbió en /reports/journal, que es LA pantalla",
  "/ketones-log": "Ketones Log — Registro de cetonas de 3 fuentes (#113, MB-8): sangre (β-hidroxibutirato mmol/L) · aliento (acetona ppm) · orina (cualitativa).",
  "/kit": "La sala ATP (MB-19 PIEZA 2) — el lanzador. Sin carpetas: secciones. Las apps caben en un scroll, y una carpeta cobraría",
  "/labs-guide": "Guía de Laboratorios — pantalla in-app (Sprint LABS GUÍA DESCARGABLE T2/T3). Renderiza la guía completa desde constants (usable sin PDF) + botón para",
  "/legal/aviso": "Sprint Compliance 2 — Aviso de Privacidad Integral (staging in-app).",
  "/legal/terminos": "Sprint Compliance 2 — Términos y Condiciones (staging in-app).",
  "/lista-compra": "Lista de compra — redirect (OLA3 · Anexo D §1). Es la pestaña Lista de /cocina, dueña única de shopping_list_items.",
  "/log-cardio": "Log Cardio (MB-3.6 Bloque 3.1) — la casa COMPLETA del cardio (Ola 2 Fitness PR2, ANEXO_B_FITNESS §1): registro manual ULTRA-fácil + PRs por",
  "/log-exercise": "Redirect legacy (Ola 2 Fitness PR3, ANEXO_B_FITNESS §5). El registro retro de fuerza vive en /log-strength (adelgazado: sin",
  "/log-strength": "Log Strength — registro RETRO de fuerza en 3 pasos (Ola 2 Fitness PR2, ANEXO_B_FITNESS §3; ex /log-exercise, adelgazado).",
  "/login": "Pantalla de Login — Entry point de la app. Branding ELITE + campos de email/password + links a registro y recuperación.",
  "/medidas": "Medidas (MB-27 Pieza 1) — la app de peso y medidas del usuario. Desbloquea \"Bajar grasa\": el pack cuyo resultado no se podía ver. Lee la",
  "/meditation": "Meditación — destino consolidado del pilar (Overhaul A2 + Ajuste 2). Un solo destino con secciones internas del catálogo `audio_pieces`:",
  "/mente/nback": "N-Back — home del módulo (norte UX: referencia de Enrique, piel ATP). Week-strip · card Reto 20 días · card Hoy 0/12 con EMPEZAR SESIÓN ·",
  "/mente/nback/como-jugar": "N-Back — cómo jugar (tutorial; primera vez es la puerta obligada a la sesión con N=1 forzado — decisión #44-1).",
  "/mente/nback/personalizar": "N-Back — Personalizar (V1.5 #C7): toda la config del módulo agrupada fuera de la home (que queda de foco). Client-only vía AsyncStorage",
  "/mente/nback/saber-mas": "N-Back — Saber más (artículo in-app). Contenido: R and D/ARTICULO_NBACK_SABER_MAS.md — voz ATP directa y",
  "/mente/nback/sesion": "N-Back — sesión activa (norte UX: referencia de Enrique). Countdown (¿Listo? / En posición. / ¡Va!) → gameplay full-black (grid 3×3",
  "/mente/nback/stats": "Redirect legacy (OLA1 R-4, ANEXO_A_REPORTS §6). Las estadísticas de N-Back son hoy /reports/nback, con sus mismas tres",
  "/mente/player": "Sprint Audio Mente — Player de audio del pilar Mente. Portada full-bleed + título + controles (play/pause, scrubber con seek,",
  "/mente/progreso": "Redirect legacy (OLA1 R-5, ANEXO_A_REPORTS §6). Las rachas y las medallas se absorbieron en /reports/adherencia, pestaña",
  "/mobility-assessment": "Evaluación de Movilidad (MB-3.6 Bloque 2) — captura GUIADA real de los 7 tests que persiste mobility_assessments (antes: placeholder de 50 líneas).",
  "/my-chronotype": "Redirect legacy (Ola 4, Anexo C, pieza 5). La vista de TU cronotipo se mudó a /tests/resultado/cronotipo, que es la",
  "/my-health": "Mi Salud — Cliente sube estudios de laboratorio y ve resultados.",
  "/my-recipes": "Mis recetas — redirect (OLA3 · Anexo D §1). Es la pestaña Recetas de /cocina, dueña de user_recipes.",
  "/my-routines": "Mis Rutinas — Lista de rutinas guardadas del usuario. Muestra todas las rutinas (timer + routine) con nombre, modo, # bloques y fecha.",
  "/night-filter": "MB-30B Pieza 1 — Filtro nocturno de sistema. Android: overlay real encima de TODO el teléfono (tipo Twilight), con",
  "/notifications": "/notifications (AGENDA-COMPLETE F3) — inbox de notificaciones in-app. Historial de user_notifications (recordatorios de agenda + futuros tipos) con marcar",
  "/nutrition": "Nutrición Hub — navegación del pilar, no tablero (OLA3 · Anexo D §1). loadData hacía 5 lecturas que computeAndSaveDailyScore YA hacía por su",
  "/onboarding/v2/chronotype": "Onboarding v2 — Paso 5: Cronotipo rápido (5 preguntas, scoring portado del quiz v1). Guarda lion/bear/wolf/dolphin + horarios en user_chronotype",
  "/onboarding/v2/consent": "Onboarding v2 — Paso 6: Consentimiento médico + disclaimers. El usuario acepta explícitamente antes de recibir cualquier recomendación.",
  "/onboarding/v2/cycle": "Onboarding v2 — Paso 4: Modalidad de Ciclo (task #111). Opciones según sexo biológico (capturado en el paso 2):",
  "/onboarding/v2/goal": "Onboarding v2 — Paso 3: Objetivo principal (5 opciones del spec: longevidad / composición / energía / deporte / preparación).",
  "/onboarding/v2/notifications": "Onboarding v2 — Paso 7: Permiso de notificaciones (explicación clara ANTES del prompt del sistema). Al terminar (con o sin permiso) el onboarding se",
  "/onboarding/v2/positioning": "Onboarding v2 — Paso 2: Posicionamiento (Sprint Compliance 4). Versión PRECISA del posicionamiento (POSICIONAMIENTO_MASTER §2, citada en",
  "/onboarding/v2/privacy": "Onboarding v2 — Paso 2: Muro de consentimiento (Sprint Compliance 2). Aviso de Privacidad Simplificado (Parte 2) arriba + checkboxes de la",
  "/onboarding/v2/profile": "Onboarding v2 — Paso 2: Perfil base (sexo biológico, fecha de nacimiento, altura y peso). Los 4 son obligatorios: alimentan Edad ATP desde el día 1.",
  "/onboarding/v2/welcome": "Onboarding v2 — Paso 1: Bienvenida (nombre; la foto se agrega después en Perfil — decisión de criterio: no meter picker/upload en el primer paso).",
  "/onboarding/voice-config": "Onboarding — Voice Config (paso 9). Wizard auto-advance de 16 preguntas que pueblan `coach_voice_config`.",
  "/ordenar-dia": "Ordenar mi día (MB-26 Pieza 4) — la salida al desmadre. Tres caminos, uno por pantalla: empezar de cero (todo a reposo),",
  "/packs/armar": "Ármala por mí — la entrada de dos preguntas (MB-25 Pieza 3, en etapas desde MB-26 Pieza 7).",
  "/paywall": "PAYWALL — editorial ATP (negro + lima). 2 planes (Base con 14 días trial · Pro sin trial, RECOMENDADO) con toggle",
  "/perfil": "Tab vieja Perfil — redirect para deep links externos (OLA0 QW-6).",
  "/plan-entrenamiento": "Mi plan de entrenar (MB-27 Pieza 2) — el usuario dice UNA vez qué días entrena qué, y Entrenar le contesta \"hoy te toca X\".",
  "/profile": "Perfil — identidad del usuario: nombre, fecha de nacimiento (calcula edad cronológica), sexo biológico. Accesible desde el header de YO (Mariana #1:",
  "/progreso": "Tab vieja Progreso — redirect para deep links externos (OLA0 QW-6).",
  "/progress": "Mi Progreso — Resumen mensual, gráficas de frecuencia/volumen semanal, y lista de PRs recientes.",
  "/protocol-explorer": "ProtocolExplorer — Pantalla donde el cliente explora y activa plantillas de protocolos. Muestra protocolos activos del usuario y la galería de plantillas públicas.",
  "/quiz-take": "Redirect legacy (Ola 4, Anexo C, pieza 5). El quiz de base de datos lo corre el motor único de /tests/q/[id], que",
  "/quiz/chronotype": "Redirect legacy (Ola 4, Anexo C, pieza 5). El cronotipo lo corre el motor unico. La rama de onboarding que tenia esta",
  "/quizzes": "Redirect legacy (Ola 4, Anexo C, pieza 5). Uno de los seis hubs que ensenaban lo mismo desde angulos distintos. Lo absorbio el hub unico /tests, que lee",
  "/redeem-code": "TENGO UN CÓDIGO — canje de códigos de activación (MB-13 · PIEZA 1). Para el founder que pagó en la web, el invitado o la cortesía de soporte.",
  "/register": "Pantalla de Registro — Crear cuenta nueva. Campos: nombre completo, email, password, confirmar password.",
  "/reports": "Reports — Hub de reportes en GradientCard: Identidad, Calendario de adherencia, Electrones, Nutrición, Hidratación, Ayuno, Ejercicio, Glucosa,",
  "/reset-password": "Reset de contraseña — el flujo vivo es forgot-password + página web somosatp.com/reset-password (auth-context, task #43). Redirect (OLA0 QW-6).",
  "/routine-generator": "Routine Generator — 3 puertas sobre el motor determinista (MB-3 Track F; INTERVALOS desde Ola 2 Fitness PR2, ANEXO_B_FITNESS §1).",
  "/salud": "Tab SALUD — hero de Edad ATP y las cuatro secciones. OLA6 PIEZA B: el contenido vive en SaludHub y esta es su ÚNICA montura.",
  "/salud/cuestionario-maestro": "Redirect legacy (Ola 4, Anexo C, pieza 5). El Cuestionario Maestro corre en el motor unico, que nacio de su propio",
  "/salud/diagnostico": "Card A — \"Mi Diagnóstico Funcional\" (DX+Intervenciones F2). Documento VIVO y versionado: nivel de calidad 1-5, \"qué te falta\" para subir,",
  "/salud/evolucion": "/salud/evolucion — ya no es pantalla, es un puente. OLA6 PIEZA A: TU EVOLUCIÓN vive como sección del tab SALUD. La ruta se",
  "/salud/expediente": "/salud/expediente — ya no es pantalla, es un puente. OLA6 PIEZA A: MI EXPEDIENTE vive como sección del tab SALUD. La ruta se",
  "/salud/ficha-emergencia": "/salud/ficha-emergencia — la ficha que lee alguien más. OLA6 PIEZA D. Toda la pantalla obedece a una sola escena: estás en el piso,",
  "/salud/hoy": "/salud/hoy — ya no es pantalla, es un puente. OLA6 PIEZA A: HOY EN TU CUERPO dejó de ser una ruta con su propio cascarón.",
  "/salud/intervenciones": "Intervenciones (dx-f3) — \"Mi Protocolo\" completo + \"Sugeridas para ti\". Mi Protocolo = activas (completar hoy + pausar). Sugeridas = output del motor",
  "/salud/intervenciones/rationale": "¿POR QUÉ ESTAS INTERVENCIONES? — narrativa ARGOS (Megabuzón 2da pasada B.4). Doctrina H+: se COBRA con Protones (280 H+, precio server-side; Pro efectivo",
  "/salud/mi-expediente": "MI EXPEDIENTE — timeline cronológico del registro epigenético (Mega-Sprint B · B5). Eje temporal que cruza síntomas (inicio/fin), intervenciones activadas, labs y",
  "/salud/mis-datos": "MIS DATOS — destino ÚNICO de todo dato numérico de salud (Mega-Sprint B · B2). Consolida lo que estaba disperso en 8 pantallas / 2 árboles (health-input,",
  "/salud/mis-evaluaciones": "Redirect legacy (Ola 4, Anexo C, pieza 5). Mis evaluaciones era el mismo listado con otro molde. Lo absorbio el hub unico /tests, que lee",
  "/salud/mis-sintomas": "MIS SÍNTOMAS — destino ÚNICO del síntoma (Mega-Sprint B · B3). Absorbe las 3 superficies viejas (sintomas.tsx sueltos + clinical-system.tsx",
  "/salud/padecimientos": "Padecimientos (SALUD F5) — registro ligero de condiciones + episodios (recurrencia). Modelo normalizado de la migración 173: padecimiento = definición de la",
  "/salud/sintomas": "Síntomas Aislados (SALUD F5) — quick-tap de síntomas sueltos, peso BAJO en el DX. Chips de síntomas frecuentes de medicina funcional + input libre, severidad",
  "/session": "/session — runner UNIFICADO de entrenamiento (Ola 2 Fitness PR1; ex strength-session, MB-3 Tracks D+E+F). /strength-session queda como alias",
  "/settings": "AJUSTES — hub principal (#137, testing fixes V1.3). Reorganización tipo iOS/Android Settings: 7 grupos navegables + Developer",
  "/settings/comunidad": "Settings > Comunidad — visibilidad granular del perfil público + username + bridge Skool. Mapa Comunidad C1. Persiste en user_profile_public (mig 177) al",
  "/settings/conexiones": "AJUSTES › CONEXIONES (#137) — coach, atletas, wearables y afiliados. (Movido del monolito: secciones CONECTAR CON COACH + SOY COACH + DISPOSITIVOS.)",
  "/settings/cuenta": "AJUSTES › PERFIL Y CUENTA (#137) — foto, datos, plan y sesión. La edición real de identidad (nombre/fecha/sexo/foto) vive en /profile;",
  "/settings/dev": "AJUSTES › DEVELOPER (#137) — solo __DEV__ o admins (founders/team).",
  "/settings/experiencia": "AJUSTES › EXPERIENCIA (#137) — tema, idioma, unidades, voz, sonidos, vibración, pantalla y zona de prueba. (Antes: 6 secciones del monolito.)",
  "/settings/legal": "Settings > Legal (#42) — documentos legales y disclaimers médicos. Links a Privacy Policy / Terms (somosatp.com) + re-lectura del modal de",
  "/settings/notifications": "Settings > Notificaciones (#61) — control granular: modos (standard / adaptive ARGOS / silent), toggles por tipo,",
  "/settings/privacy": "Settings > Privacidad (#132 Privacy Fase B) — control total del usuario: A) Consent toggles (user_consent, migración 100)",
  "/settings/salud": "AJUSTES › SALUD Y PROTOCOLO (#137) — cronotipo, protocolos, fitness, nutrición, ciclo e historia clínica.",
  "/settings/subscription": "AJUSTES › SUSCRIPCIÓN — estado del plan, renovación, gestión e historial. La cancelación real vive en Apple/Google (no se puede cancelar in-app por",
  "/shared-routine": "Redirect legacy (Ola 2 Fitness PR3, ANEXO_B_FITNESS §5). El preview de rutina compartida es el sheet ?share=CODE de /my-routines",
  "/sleep": "Sueño (#15 Batch 2) — pantalla editorial propia del descanso. Antes SUEÑO caía en /reports (hub genérico) o /health-hub. Esta pantalla se ve",
  "/sleep-session": "Sesión nocturna del Sleep Cycle (MB-30A · Pieza 1). El modelo: la app abierta toda la noche en el buró, teléfono cargando,",
  "/solar": "ATP SOL — Exposición solar consciente. Filosofía:",
  "/strength-session": "Alias permanente de /session (Ola 2 Fitness PR1, ANEXO_B_FITNESS §5). La ruta vieja sigue viva y rinde el mismo runner con los mismos params:",
  "/supplements": "Suplementos — REGISTRO personal con tracking, agrupado por momento del día. Doctrina (Sprint SUPS+BHA): suplementos son REGISTRO, no recomendación.",
  "/tests": "TESTS — hub único de evaluaciones (Ola 4, Anexo C, pieza 2). Absorbe seis hubs que hoy muestran lo mismo desde ángulos distintos:",
  "/tests/resultado/cronotipo": "Mi Cronotipo — la vista de TU cronotipo, no el test crudo. Ola 4, pieza 5: se mudó de /my-chronotype a /tests/resultado/cronotipo, que",
  "/tribu": "Tab TRIBU (MB-19 PIEZA 4) — la casa de la comunidad. Antes se llegaba por una card dentro de Mi ATP, que este run convirtió en la",
};
