/**
 * MATRIZ DE SALUD FUNCIONAL — V7 HOMBRES / V6 MUJERES
 * Fuente: Matriz_calculo_salud_funcional_MasterV7_HOMBRES.xlsx + MasterV6_MUJERES.xlsx
 * Autor: Enrique Zapata + Mariana Doria (Co-Founder & CSO)
 * Extraído: 2026-06-09 desde los Excel master.
 *
 * 9 bandas por parámetro. Lógica: `value <= bandLimits[i]` → `SCORES_9[i]`.
 * Si value > último límite definido → SCORES_9[8] (Fuera de rango / Crítico).
 * `null` en bandLimits = banda no aplicable (saltar al siguiente límite).
 */

export const SCORES_9 = [0, 25, 50, 80, 100, 80, 50, 25, 0] as const;
export const BAND_NAMES = [
  'critico_-5', 'riesgo_-4', 'aceptable_-3', 'optimo_1', 'optimo_2',
  'aceptable_3', 'riesgo_4', 'critico_5', 'fuera_de_rango',
] as const;

export type MatrizParam = {
  key: string;
  name: string;
  unit: string | null;
  weight: number;
  source: string | null;
  bandLimits: (number | null)[]; // 8 límites superiores
};

export type MatrizDomain = {
  domain_key: string;
  domain_name_es: string;
  params: MatrizParam[];
};

export type MatrizSexo = Record<string, MatrizDomain>;


export const MATRIZ_HOMBRES: MatrizSexo = {
  cardiovascular: {
    domain_key: "cardiovascular",
    domain_name_es: "Cardiovascular",
    params: [
  { key: "apolipoproteinas_b", name: "Apolipoproteinas B", unit: "mg/dl", weight: 0.15, source: "Laboratorio", bandLimits: [30, 0, 40, 50, 99, 110, 125, 150] },
  { key: "bilirrubina", name: "Bilirrubina", unit: "mg/dl", weight: 0.02, source: "Laboratorio", bandLimits: [null, null, null, 0.3, 1, 1.2, 1.5, 1.6] },
  { key: "colesterol_hdl", name: "Colesterol HDL", unit: "mg/dl", weight: 0.04, source: "Laboratorio", bandLimits: [30, 40, 50, 60, 100, null, null, null] },
  { key: "colesterol_ldl", name: "Colesterol LDL", unit: "mg/dl", weight: 0.01, source: "Laboratorio", bandLimits: [30, 50, 60, 80, 120, 150, 160, 180] },
  { key: "colesterol_total", name: "Colesterol total", unit: "mg/dl", weight: 0.01, source: "Laboratorio", bandLimits: [115, 130, 150, 180, 220, 250, 280, 350] },
  { key: "frecuencia_cardiaca_en_reposo_sueno", name: "Frecuencia cardiaca en reposo (sue\u00f1o)", unit: "ppm", weight: 0.04, source: "Wearable", bandLimits: [null, null, null, 35, 55, 64, 70, 75] },
  { key: "gama_glutamil_transferasa", name: "Gama Glutamil transferasa", unit: "U/l", weight: 0.04, source: "Laboratorio", bandLimits: [0, 5, 8, 10, 25, 35, 50, 55] },
  { key: "indice_aterogenico", name: "Indice Aterogenico", unit: "Ratio", weight: 0.03, source: "Laboratorio", bandLimits: [null, null, 0.1, 0.2, 2.5, 3.5, 4.5, 6] },
  { key: "indice_de_lipoproteinas_ldlhdl", name: "indice de lipoproteinas (LDL/HDL)", unit: "Ratio", weight: 0.04, source: "Calculo", bandLimits: [0, 0, 0, 0.1, 2, 2.5, 3.5, 4] },
  { key: "presion_sistolica", name: "Presion sistolica", unit: "mm/mg", weight: 0.08, source: "Forms/Entrevista", bandLimits: [75, 80, 90, 100, 115, 120, 129, 140] },
  { key: "presion_diastolica", name: "Presion diastolica", unit: "mm/mg", weight: 0.05, source: "Forms/Entrevista", bandLimits: [45, 50, 60, 65, 75, 80, 85, 90] },
  { key: "relacion_neutrofilos_linfocitos_nlr", name: "Relacion Neutrofilos / Linfocitos (NLR)", unit: "Ratio", weight: 0.05, source: "Calculo", bandLimits: [null, null, null, 0.1, 1.5, 2, 2.2, 2.5] },
  { key: "relacion_trigliceridos_hdl", name: "Relacion Trigliceridos / HDL", unit: "Ratio", weight: 0.06, source: "Calculo", bandLimits: [null, null, null, 0.1, 1.8, 2, 2.5, 2.8] },
  { key: "respiracion_bolt", name: "Respiracion BOLT", unit: "Seg", weight: 0.04, source: "Tests", bandLimits: [12, 15, 20, 25, 60, null, null, null] },
  { key: "sdldl", name: "sdLDL", unit: "mg/dl", weight: 0.06, source: "Laboratorio", bandLimits: [null, null, 0, 5, 20, 30, 40, 50] },
  { key: "transaminasa_glutamico_oxalacetica_ast", name: "Transaminasa Glutamico Oxalacetica (AST)", unit: "U/l", weight: 0.02, source: "Laboratorio", bandLimits: [0, 5, 10, 15, 25, 35, 45, 50] },
  { key: "transaminasa_glutamico_piruvica_alt", name: "Transaminasa Glutamico Piruvica (ALT)", unit: "U/l", weight: 0.02, source: "Laboratorio", bandLimits: [0, 5, 10, 15, 25, 35, 45, 50] },
  { key: "trigliceridos", name: "Trigliceridos", unit: "mg/dl", weight: 0.03, source: "Laboratorio", bandLimits: [null, null, null, 30, 70, 100, 150, 175] },
  { key: "vldl", name: "VLDL", unit: "mg/dl", weight: 0.03, source: "Laboratorio", bandLimits: [0, 1, 2, 5, 15, 20, 30, 35] },
  { key: "vo2_estimado", name: "VO2 estimado", unit: "ml/kg/min", weight: 0.09, source: "Tests", bandLimits: [30, 36, 42, 50, 100, null, null, null] },
  { key: "hemoglobina", name: "Hemoglobina", unit: "g/dl", weight: 0.03, source: "Tests", bandLimits: [9, 11, 12, 14, 15, 15.5, 16, 17] },
  { key: "hematocrito", name: "Hematocrito", unit: "%", weight: 0.02, source: "Tests", bandLimits: [0.33, 0.34, 0.36, 0.38, 0.44, 0.49, 0.52, 0.54] },
  { key: "rdw_cv", name: "RDW - CV", unit: "%", weight: 0.04, source: "Tests", bandLimits: [0.03, 0.04, 0.05, 0.06, 0.125, 0.135, 0.145, 0.155] },
    ],
  },
  composicion_corporal: {
    domain_key: "composicion_corporal",
    domain_name_es: "Composici\u00f3n corporal",
    params: [
  { key: "grasa_corporal", name: "% grasa corporal", unit: "%", weight: 0.18, source: "Forms/Entrevista", bandLimits: [0.03, 0.07, 0.08, 0.1, 0.14, 0.185, 0.24, 0.35] },
  { key: "musculo_esqueletico", name: "% musculo esqueletico", unit: "%", weight: 0.19, source: "Forms/Entrevista", bandLimits: [0.2, 0.3, 0.35, 0.4, 0.6, 0.7, 0.75, 0.8] },
  { key: "edad_corporal", name: "Edad corporal", unit: "a\u00f1os", weight: 0.08, source: "Forms/Entrevista", bandLimits: [null, null, null, -15, -1, 0, 5, 10] },
  { key: "fuerza_de_agarre", name: "Fuerza de agarre", unit: "Kg", weight: 0.13, source: "Forms/Entrevista", bandLimits: [35, 40, 45, 50, 100, null, null, null] },
  { key: "grasa_visceral", name: "Grasa visceral", unit: "Unidad", weight: 0.1, source: "Forms/Entrevista", bandLimits: [0, 0, 0, 1, 2, 9, 12, 15] },
  { key: "pullups", name: "Pull-ups", unit: "cantidad", weight: 0.03, source: "Forms/Entrevista", bandLimits: [3, 6, 10, 15, 50, null, null, null] },
  { key: "pushups", name: "Push-ups", unit: "cantidad", weight: 0.03, source: "Tests", bandLimits: [15, 20, 30, 40, 100, null, null, null] },
  { key: "sentadilla_libre", name: "Sentadilla libre", unit: "Unidad", weight: 0.03, source: "Tests", bandLimits: [8, 10, 20, 30, 80, null, null, null] },
  { key: "test_de_equilibrio_en_un_pie", name: "Test de equilibrio en un pie", unit: "Seg", weight: 0.05, source: "Tests", bandLimits: [7, 10, 20, 30, 60, null, null, null] },
  { key: "vo2_max", name: "VO2 Max", unit: "ml/kg/min", weight: 0.18, source: "Tests", bandLimits: [30, 36, 42, 50, 100, null, null, null] },
    ],
  },
  habitos: {
    domain_key: "habitos",
    domain_name_es: "Habitos",
    params: [
  { key: "amalgamas_de_mercurio", name: "Amalgamas de mercurio", unit: "cantidad", weight: 0.04, source: "Forms/Entrevista", bandLimits: [null, null, null, -1, 0, 0, 1, 2] },
  { key: "ayuno_intermitente", name: "Ayuno intermitente", unit: "hr/dia", weight: 0.12, source: "Forms/Entrevista", bandLimits: [12, 13, 14, 16, 20, 23, null, null] },
  { key: "consistencia_en_ejercicio_semanal", name: "Consistencia en ejercicio semanal", unit: "veces/semana", weight: 0.1, source: "Forms/Entrevista", bandLimits: [1, 2, 3, 5, 8, 12, 18, 20] },
  { key: "consumo_de_alcohol_mensual", name: "Consumo de alcohol mensual", unit: "copas/mes", weight: 0.08, source: "Forms/Entrevista", bandLimits: [null, null, null, 0, 4, 6, 10, 16] },
  { key: "salud_de_encias", name: "Salud de encias", unit: "evento", weight: 0.1, source: "Forms/Entrevista", bandLimits: [null, null, null, -1, 0, 1, 2, 3] },
  { key: "uso_de_farmacos_cronicos", name: "Uso de farmacos cronicos", unit: "cantidad", weight: 0.08, source: "Forms/Entrevista", bandLimits: [null, null, null, -1, 0, 1, 2, 3] },
  { key: "ejercicio_semanal", name: "Ejercicio semanal", unit: "hr/semana", weight: 0.2, source: "Forms/Entrevista", bandLimits: [2, 4, 7, 10, 25, 28, 30, 32] },
  { key: "uso_de_pantallas_hrdia", name: "Uso de pantallas hr/dia", unit: "hr/dia", weight: 0.06, source: "Forms/Entrevista", bandLimits: [null, null, null, 0, 4, 6, 8, 10] },
  { key: "pasos_al_dia", name: "Pasos al d\u00eda", unit: "Pasos/dia", weight: 0.05, source: "Forms/Entrevista", bandLimits: [5000, 5500, 6500, 7800, 15000, 25000, null, null] },
  { key: "tabaquismo", name: "Tabaquismo", unit: "Cigarros/d\u00eda", weight: 0.08, source: "Forms/Entrevista", bandLimits: [null, null, null, -1, 0, 0, 1, 2] },
  { key: "respiracion_consciente", name: "Respiracion consciente", unit: "min/dia", weight: 0.04, source: "Forms/Entrevista", bandLimits: [2, 5, 8, 10, 90, 180, null, null] },
  { key: "minutos_de_luz_natural", name: "Minutos de luz natural", unit: "min/dia", weight: 0.05, source: "Forms/Entrevista", bandLimits: [2, 5, 10, 25, 90, 180, null, null] },
    ],
  },
  inflamacion: {
    domain_key: "inflamacion",
    domain_name_es: "Inflamaci\u00f3n",
    params: [
  { key: "acido_urico", name: "Acido urico", unit: "mg/dl", weight: 0.06, source: "Laboratorio", bandLimits: [null, null, 3, 4, 6, 7, 8, 9] },
  { key: "factor_reumatoide", name: "Factor reumatoide", unit: "UI/ml", weight: 0.07, source: "Laboratorio", bandLimits: [null, null, 0, 1, 10, 15, 20, 25] },
  { key: "ferritina", name: "Ferritina", unit: "ng/ml", weight: 0.07, source: "Laboratorio", bandLimits: [5, 10, 20, 50, 150, 200, 300, 400] },
  { key: "ggt", name: "GGT", unit: "U/l", weight: 0.08, source: "Laboratorio", bandLimits: [0, 5, 8, 10, 25, 35, 50, 55] },
  { key: "homocisteina", name: "Homocisteina", unit: "mcmol/ml", weight: 0.15, source: "Laboratorio", bandLimits: [1, 2, 4, 5, 9, 12, 14, 17] },
  { key: "proteina_c_reactiva_cuantitativa_pcr", name: "Proteina C reactiva cuantitativa (PCR)", unit: "mg/dl", weight: 0.2, source: "Laboratorio", bandLimits: [null, null, null, 0, 0.2, 0.4, 0.6, 0.7] },
  { key: "tiempo_de_recuperacion_postejercicio", name: "Tiempo de recuperacion post-ejercicio", unit: "min", weight: 0.05, source: "Tests", bandLimits: [null, null, null, 1, 24, 36, 48, 50] },
  { key: "transaminasa_g_oxalacetica_ast_tgo", name: "Transaminasa G Oxalacetica AST (TGO)", unit: "U/l", weight: 0.03, source: "Laboratorio", bandLimits: [null, null, null, 1, 25, 35, 45, 46] },
  { key: "vitamina_d", name: "Vitamina D", unit: "ng/ml", weight: 0.13, source: "Laboratorio", bandLimits: [20, 30, 40, 50, 80, 90, 100, 105] },
  { key: "relacion_neutrofilos_linfocitos_nlr", name: "Relacion Neutrofilos / Linfocitos (NLR)", unit: "Ratio", weight: 0.11, source: "Calculo", bandLimits: [null, null, null, 0.1, 1.5, 2, 2.2, 2.5] },
  { key: "ldh", name: "LDH", unit: "Ratio", weight: 0.05, source: "Calculo", bandLimits: [109, 120, 135, 167, 187, 205, 220, 246] },
    ],
  },
  inmunidad: {
    domain_key: "inmunidad",
    domain_name_es: "Inmunidad",
    params: [
  { key: "antiestreptolisinas", name: "Antiestreptolisinas", unit: "UI/ml", weight: 0.11, source: "Laboratorio", bandLimits: [null, null, null, 0, 100, 200, 400, 500] },
  { key: "bilirrubina", name: "Bilirrubina", unit: "mg/dl", weight: 0.1, source: "Laboratorio", bandLimits: [null, null, null, 0.3, 1, 1.2, 1.5, 1.6] },
  { key: "iga", name: "IgA", unit: "mg/dl", weight: 0.08, source: "Laboratorio", bandLimits: [79, 80, 100, 120, 250, 300, 400, 401] },
  { key: "ige", name: "IgE", unit: "UI/ml", weight: 0.06, source: "Laboratorio", bandLimits: [null, null, null, 10, 40, 60, 100, 101] },
  { key: "igg", name: "IgG", unit: "mg/dl", weight: 0.1, source: "Laboratorio", bandLimits: [599, 600, 700, 800, 1200, 1300, 1400, 1401] },
  { key: "igm", name: "IgM", unit: "mg/dl", weight: 0.06, source: "Laboratorio", bandLimits: [39, 40, 60, 80, 150, 180, 220, 221] },
  { key: "indice_de_bilirrubina", name: "indice de bilirrubina", unit: "Ratio", weight: 0.06, source: "Laboratorio", bandLimits: [null, null, null, 0.05, 0.3, 0.5, 0.8, 0.9] },
  { key: "leucocitos_totales", name: "Leucocitos totales", unit: "/mcl", weight: 0.11, source: "Laboratorio", bandLimits: [3000, 4000, 4500, 5000, 8000, 9000, 10000, 12000] },
  { key: "proteina_c_reactiva_cuantitativa_pcr", name: "Proteina C reactiva cuantitativa (PCR)", unit: "mg/dl", weight: 0.08, source: "Laboratorio", bandLimits: [null, null, null, 0, 0.2, 0.4, 0.6, 0.7] },
  { key: "vitamina_d", name: "Vitamina D", unit: "ng/ml", weight: 0.08, source: "Laboratorio", bandLimits: [20, 30, 40, 50, 80, 90, 100, 110] },
  { key: "relacion_neutrofilos_linfocitos_nlr", name: "Relacion Neutrofilos / Linfocitos (NLR)", unit: "Ratio", weight: 0.11, source: "Calculo", bandLimits: [null, null, null, 0.1, 1.5, 2, 2.2, 2.5] },
  { key: "ldh", name: "LDH", unit: "Ratio", weight: 0.05, source: "Calculo", bandLimits: [5, 10, 15, 20, 200, 300, 400, 500] },
    ],
  },
  metabolismo: {
    domain_key: "metabolismo",
    domain_name_es: "Metabolismo",
    params: [
  { key: "coeficiente_de_variabilidad_cv", name: "Coeficiente de variabilidad CV", unit: "score", weight: 0.05, source: "Glucometro", bandLimits: [null, null, null, 0.01, 0.18, 0.22, 0.28, 0.29] },
  { key: "flexibilidad_metabolica_subjetiva_puntuacion_de_test_ayuno", name: "Flexibilidad metabolica subjetiva (puntuacion de test ayuno)", unit: "score", weight: 0.06, source: "Tests", bandLimits: [40, 60, 80, 90, 100, null, null, null] },
  { key: "glucosa_en_ayuno", name: "Glucosa en ayuno", unit: "mg/dl", weight: 0.09, source: "Laboratorio", bandLimits: [25, 35, 45, 70, 85, 90, 99, 110] },
  { key: "glucosa_media_cgm", name: "Glucosa Media (CGM)", unit: "mg/dl", weight: 0.08, source: "Glucometro", bandLimits: [25, 35, 45, 70, 95, 105, 115, 120] },
  { key: "hba1c", name: "HbA1c %", unit: "%", weight: 0.14, source: "Laboratorio", bandLimits: [0.01, 0.025, 0.035, 0.049, 0.052, 0.056, 0.058, 0.06] },
  { key: "homair", name: "HOMA-IR", unit: "Ratio", weight: 0.11, source: "Laboratorio", bandLimits: [null, null, null, 0.1, 1, 1.5, 2, 3] },
  { key: "indice_aterogenico", name: "Indice Aterogenico", unit: "Ratio", weight: 0.05, source: "Laboratorio", bandLimits: [null, null, null, 0.1, 2.5, 3.5, 4.5, 6] },
  { key: "insulina", name: "Insulina", unit: "mgUI/ml", weight: 0.07, source: "Laboratorio", bandLimits: [null, null, null, 2, 6, 8, 10, 15] },
  { key: "moda_vs_media_cgm", name: "Moda VS Media (CGM)", unit: "Ratio", weight: 0.01, source: "Glucometro", bandLimits: [-16, -15, -10, -5, 5, 10, 15, 16] },
  { key: "numero_de_ingestas_al_dia", name: "Numero de ingestas al dia", unit: "cantidad", weight: 0.04, source: "Forms/Entrevista", bandLimits: [null, null, null, 1, 2, 3, 4, 5] },
  { key: "relacion_trigliceridos_hdl", name: "Relacion Trigliceridos / HDL", unit: "Ratio", weight: 0.07, source: "Calculo", bandLimits: [null, null, null, 0.1, 1.8, 2, 2.5, 2.8] },
  { key: "tiempo_en_rango_saludable_65150_cgm", name: "Tiempo en rango saludable [65-150] (CGM)", unit: "%", weight: 0.08, source: "Glucometro", bandLimits: [0.69, 0.7, 0.8, 0.9, 1, null, null, null] },
  { key: "trigliceridos", name: "Trigliceridos", unit: "mg/dl", weight: 0.04, source: "Laboratorio", bandLimits: [null, null, null, 30, 70, 100, 150, 175] },
  { key: "variabilidad_glucemica_cgm_sd", name: "Variabilidad glucemica (CGM) (SD)", unit: "score", weight: 0.03, source: "Glucometro", bandLimits: [null, null, null, 0, 15, 20, 25, 26] },
  { key: "ggt", name: "GGT", unit: "U/l", weight: 0.04, source: "Laboratorio", bandLimits: [0, 5, 8, 10, 25, 35, 50, 55] },
  { key: "transaminasa_glutamico_piruvica_alt", name: "Transaminasa Glutamico Piruvica (ALT)", unit: "U/l", weight: 0.04, source: "Laboratorio", bandLimits: [0, 5, 10, 15, 25, 35, 45, 50] },
    ],
  },
  renal_y_micronutrientes: {
    domain_key: "renal_y_micronutrientes",
    domain_name_es: "Renal y Micronutrientes",
    params: [
  { key: "acido_urico", name: "Acido Urico", unit: "mg/dl", weight: 0.1, source: "Laboratorio", bandLimits: [null, null, 3, 3.5, 5.5, 6.5, 7.5, 8] },
  { key: "capacidad_de_fijacion_de_hierro", name: "Capacidad de fijacion de hierro", unit: "mcg/dl", weight: 0.05, source: "Laboratorio", bandLimits: [150, 200, 220, 250, 400, 450, 500, 550] },
  { key: "cloro", name: "Cloro", unit: "mE1/L", weight: 0.04, source: "Laboratorio", bandLimits: [93, 95, 98, 100, 106, 108, 110, 115] },
  { key: "creatinina_serica", name: "Creatinina Serica", unit: "mg/dl", weight: 0.08, source: "Laboratorio", bandLimits: [null, null, 0.7, 0.8, 1.1, 1.2, 1.3, 1.4] },
  { key: "ferritina", name: "Ferritina", unit: "ng/ml", weight: 0.08, source: "Laboratorio", bandLimits: [5, 10, 20, 50, 150, 200, 300, 400] },
  { key: "folato_acido_folico", name: "Folato (acido folico)", unit: "ng/ml", weight: 0.06, source: "Laboratorio", bandLimits: [5.5, 6, 8, 10, 18, 20, 24, 25] },
  { key: "hierro_libre", name: "Hierro Libre", unit: "mcg/dl", weight: 0.02, source: "Laboratorio", bandLimits: [null, null, 0, 10, 100, 200, 300, 350] },
  { key: "hierro_serico", name: "Hierro serico", unit: "mcg/dl", weight: 0.03, source: "Laboratorio", bandLimits: [50, 60, 70, 80, 140, 160, 180, 190] },
  { key: "magnesio", name: "Magnesio", unit: "mg/dl", weight: 0.07, source: "Laboratorio", bandLimits: [1.6, 1.8, 2, 2.2, 2.6, 2.8, 3.2, 3.3] },
  { key: "nitrogeno_ureico_bun", name: "Nitrogeno ureico (BUN)", unit: "mg/dl", weight: 0.04, source: "Laboratorio", bandLimits: [null, null, 5, 10, 18, 20, 25, 30] },
  { key: "potasio", name: "Potasio", unit: "mE1/L", weight: 0.05, source: "Laboratorio", bandLimits: [3.3, 3.5, 3.8, 4, 4.5, 5, 5.5, 6] },
  { key: "relacion_buncreatinina", name: "Relacion BUN/Creatinina", unit: "Ratio", weight: 0.05, source: "Laboratorio", bandLimits: [null, null, null, 10, 16, 20, 25, 27] },
  { key: "saturacion_de_hierro", name: "Saturacion de hierro", unit: "%", weight: 0.04, source: "Laboratorio", bandLimits: [15, 18, 20, 25, 40, 42, 45, 50] },
  { key: "sodio", name: "Sodio", unit: "mE1/L", weight: 0.04, source: "Laboratorio", bandLimits: [125, 130, 135, 138, 142, 145, 150, 160] },
  { key: "transferrina", name: "Transferrina", unit: "mg/dl", weight: 0.03, source: "Laboratorio", bandLimits: [180, 200, 220, 250, 350, 380, 400, 450] },
  { key: "urea", name: "Urea", unit: "mg/dl", weight: 0.02, source: "Laboratorio", bandLimits: [null, null, null, 15, 30, 40, 50, 55] },
  { key: "vitamina_b12", name: "Vitamina B12", unit: "pg/ml", weight: 0.05, source: "Laboratorio", bandLimits: [350, 400, 500, 600, 900, 1000, 1200, 1500] },
  { key: "vitamina_d", name: "Vitamina D", unit: "ng/ml", weight: 0.05, source: "Laboratorio", bandLimits: [20, 30, 40, 50, 90, 100, 105, 110] },
  { key: "de_agua_corporal", name: "% de agua corporal", unit: "%", weight: 0.05, source: "Laboratorio", bandLimits: [0.45, 0.49, 0.55, 0.6, 0.69, 0.72, 0.74, 0.75] },
  { key: "calciofosforo", name: "Calcio*Fosforo", unit: "mg2/dl2", weight: 0.05, source: "Laboratorio", bandLimits: [20, 21, 25, 30, 45, 50, null, 65] },
    ],
  },
  sistema_hormonal: {
    domain_key: "sistema_hormonal",
    domain_name_es: "Sistema hormonal",
    params: [
  { key: "anticuerpos_antitiroglobulina", name: "Anticuerpos Anti-Tiroglobulina", unit: "UI/ml", weight: 0.08, source: "Laboratorio", bandLimits: [null, null, null, 0, 5, 10, 15, 20] },
  { key: "anticuerpos_antitpo", name: "Anticuerpos Anti-TPO", unit: "UI/ml", weight: 0.08, source: "Laboratorio", bandLimits: [null, null, null, 0, 10, 20, 30, 35] },
  { key: "cortisol_matutino", name: "Cortisol matutino", unit: "mcg/dl", weight: 0.15, source: "Laboratorio", bandLimits: [5, 6, 8, 10, 15, 17, 18, 20] },
  { key: "fsh", name: "FSH", unit: "mUI/ml", weight: 0.06, source: "Laboratorio", bandLimits: [0, 0, 0, 2, 6, 8, 10, 11] },
  { key: "lh", name: "LH", unit: "mUI/ml", weight: 0.06, source: "Laboratorio", bandLimits: [0.9, 1, 2, 3, 6, null, null, null] },
  { key: "prolactina", name: "Prolactina", unit: "ng/ml", weight: 0.05, source: "Laboratorio", bandLimits: [null, null, null, 3, 10, 15, 18, 20] },
  { key: "t3_libre", name: "T3 libre", unit: "ng/dl", weight: 0.1, source: "Laboratorio", bandLimits: [2.2, 2.5, 2.8, 3.2, 4.2, null, null, null] },
  { key: "testosterona_libre_pgml", name: "Testosterona libre (pg/ml)", unit: "pg/ml", weight: 0.15, source: "Laboratorio", bandLimits: [20, 22, 25, 30, 45, 60, null, null] },
  { key: "testosterona_total", name: "Testosterona total", unit: "ng/ml", weight: 0.12, source: "Laboratorio", bandLimits: [3, 4.5, 6, 7, 12, null, null, null] },
  { key: "tsh", name: "TSH", unit: "mcU/ml", weight: 0.15, source: "Laboratorio", bandLimits: [null, null, null, 0.9, 2, 2.5, 3, 3.5] },
    ],
  },
  sueno: {
    domain_key: "sueno",
    domain_name_es: "Sue\u00f1o",
    params: [
  { key: "consistencia_de_horario", name: "Consistencia de horario", unit: "min", weight: 0.2, source: "Forms/Entrevista", bandLimits: [null, null, null, 0, 45, 75, null, 90] },
  { key: "cortisol_matutino", name: "Cortisol matutino", unit: "mcg/dl", weight: 0.1, source: "Laboratorio", bandLimits: [4, 5, 6, 10, 15, 18, 20, 25] },
  { key: "duracion_promedio", name: "Duracion promedio", unit: "hrs", weight: 0.1, source: "Forms/Entrevista", bandLimits: [6, 6, 7, 7.5, 8.5, 9, 9.5, 10] },
  { key: "edad_corporal", name: "Edad corporal", unit: "diferencia de a\u00f1os", weight: 0.05, source: "Forms/Entrevista", bandLimits: [0, 0, 0, -10, -1, 0, 5, 10] },
  { key: "eficiencia_del_sueno", name: "Eficiencia del sueno", unit: "score", weight: 0.08, source: "Wearable", bandLimits: [75, 75, 80, 85, 100, null, null, null] },
  { key: "energia_al_despertar", name: "Energia al despertar", unit: "score", weight: 0.1, source: "Forms/Entrevista", bandLimits: [6, 6, 7, 9, 10, null, null, null] },
  { key: "exposicion_solar_matutina", name: "Exposicion solar matutina", unit: "min", weight: 0.1, source: "Forms/Entrevista", bandLimits: [5, 5, 15, 20, 45, null, null, null] },
  { key: "sueno_deep", name: "Sueno DEEP%", unit: "%", weight: 0.1, source: "Wearable", bandLimits: [12, 12, 15, 20, 25, null, null, null] },
  { key: "sueno_rem", name: "Sueno REM%", unit: "%", weight: 0.1, source: "Wearable", bandLimits: [15, 15, 18, 22, 27, null, null, null] },
  { key: "testosterona_total", name: "Testosterona total", unit: "ng/dl", weight: 0.07, source: "Laboratorio", bandLimits: [3, 4, 5, 7, 13, 15, 20, 25] },
    ],
  },
  vitalidad: {
    domain_key: "vitalidad",
    domain_name_es: "Vitalidad",
    params: [
  { key: "claridad_mental", name: "Claridad mental", unit: "score", weight: 0.08, source: "Forms/Entrevista", bandLimits: [5, 6, 8, 9, 10, null, null, null] },
  { key: "cortisol_matutino", name: "Cortisol matutino", unit: "mcg/dl", weight: 0.09, source: "Laboratorio", bandLimits: [5, 6, 8, 10, 15, 17, 18, 20] },
  { key: "cpk", name: "CPK", unit: "U/L", weight: 0.05, source: "Laboratorio", bandLimits: [0, 0, 25, 50, 200, 300, 500, 550] },
  { key: "edad_corporal", name: "Edad corporal", unit: "diferencia de a\u00f1os", weight: 0.06, source: "Forms/Entrevista", bandLimits: [null, null, null, -10, -1, 0, 5, 10] },
  { key: "energia_diaria", name: "Energia diaria", unit: "score", weight: 0.12, source: "Forms/Entrevista", bandLimits: [5, 6, 8, 9, 10, null, null, null] },
  { key: "fuerza_de_agarre", name: "Fuerza de agarre", unit: "kg", weight: 0.12, source: "Forms/Entrevista", bandLimits: [20, 30, 40, 50, 100, null, null, null] },
  { key: "motivacion_y_entusiasmo", name: "Motivacion y entusiasmo", unit: "score", weight: 0.05, source: "Forms/Entrevista", bandLimits: [5, 6, 8, 9, 10, null, null, null] },
  { key: "musculo_esqueletico", name: "Musculo esqueletico %", unit: "%", weight: 0.09, source: "Forms/Entrevista", bandLimits: [0.25, 0.3, 0.35, 0.4, 0.65, null, null, null] },
  { key: "resiliencia_emocional_estres", name: "Resiliencia emocional / estres", unit: "score", weight: 0.05, source: "Forms/Entrevista", bandLimits: [5, 6, 8, 9, 10, null, null, null] },
  { key: "senales_de_fatiga_cronica", name: "Se\u00f1ales de fatiga cronica", unit: "score", weight: 0.03, source: "Forms/Entrevista", bandLimits: [null, null, null, 0, 2, 4, 6, 7] },
  { key: "testosterona_libre", name: "Testosterona libre", unit: "pg/ml", weight: 0.07, source: "Laboratorio", bandLimits: [20, 22, 25, 30, 45, 60, null, null] },
  { key: "vitamina_b12", name: "Vitamina B12", unit: "pg/ml", weight: 0.06, source: "Laboratorio", bandLimits: [350, 400, 500, 600, 900, 1000, 1200, 1500] },
  { key: "vitamina_d", name: "Vitamina D", unit: "ng/ml", weight: 0.08, source: "Laboratorio", bandLimits: [20, 30, 40, 50, 80, 90, 100, 110] },
  { key: "magnesio", name: "Magnesio", unit: "mg/dl", weight: 0.05, source: "Laboratorio", bandLimits: [1.6, 1.8, 2, 2.2, 2.6, 2.8, 3.2, 3.3] },
    ],
  },
};

export const MATRIZ_MUJERES: MatrizSexo = {
  cardiovascular: {
    domain_key: "cardiovascular",
    domain_name_es: "Cardiovascular",
    params: [
  { key: "apolipoproteinas_b", name: "Apolipoproteinas B", unit: "mg/dl", weight: 0.15, source: "Laboratorio", bandLimits: [30, 0, 40, 50, 99, 110, 125, 150] },
  { key: "bilirrubina", name: "Bilirrubina", unit: "mg/dl", weight: 0.02, source: "Laboratorio", bandLimits: [0.19, 0.2, 0.4, 0.6, 1.1, 1.9, 2.9, 3] },
  { key: "colesterol_hdl", name: "Colesterol HDL", unit: "mg/dl", weight: 0.04, source: "Laboratorio", bandLimits: [30, 35, 45, 50, 70, 90, 100, 110] },
  { key: "colesterol_ldl", name: "Colesterol LDL", unit: "mg/dl", weight: 0.01, source: "Laboratorio", bandLimits: [30, 50, 60, 80, 120, 150, 160, 180] },
  { key: "colesterol_total", name: "Colesterol total", unit: "mg/dl", weight: 0.01, source: "Laboratorio", bandLimits: [115, 130, 150, 180, 220, 250, 280, 350] },
  { key: "frecuencia_cardiaca_en_reposo_sueno", name: "Frecuencia cardiaca en reposo (sue\u00f1o)", unit: "ppm", weight: 0.04, source: "Wearable", bandLimits: [null, null, null, 35, 55, 64, 70, 75] },
  { key: "gama_glutamil_transferasa", name: "Gama Glutamil transferasa", unit: "U/l", weight: 0.04, source: "Laboratorio", bandLimits: [0, 5, 8, 10, 25, 35, 50, 55] },
  { key: "indice_aterogenico", name: "Indice Aterogenico", unit: "Ratio", weight: 0.03, source: "Laboratorio", bandLimits: [null, null, 0.1, 0.2, 2.5, 3.5, 4.5, 6] },
  { key: "indice_de_lipoproteinas_ldlhdl", name: "indice de lipoproteinas (LDL/HDL)", unit: "Ratio", weight: 0.04, source: "Calculo", bandLimits: [0, 0, 0, 0.1, 2, 2.5, 3.5, 4] },
  { key: "presion_sistolica", name: "Presion sistolica", unit: "mm/mg", weight: 0.08, source: "Forms/Entrevista", bandLimits: [75, 80, 90, 100, 115, 120, 129, 140] },
  { key: "presion_diastolica", name: "Presion diastolica", unit: "mm/mg", weight: 0.05, source: "Forms/Entrevista", bandLimits: [45, 50, 60, 65, 75, 80, 85, 90] },
  { key: "relacion_neutrofilos_linfocitos_nlr", name: "Relacion Neutrofilos / Linfocitos (NLR)", unit: "Ratio", weight: 0.05, source: "Calculo", bandLimits: [null, null, null, 0.1, 1.5, 2, 2.2, 2.5] },
  { key: "relacion_trigliceridos_hdl", name: "Relacion Trigliceridos / HDL", unit: "Ratio", weight: 0.06, source: "Calculo", bandLimits: [null, null, null, 0.1, 1.8, 2, 2.5, 2.8] },
  { key: "respiracion_bolt", name: "Respiracion BOLT", unit: "Seg", weight: 0.04, source: "Tests", bandLimits: [12, 15, 20, 25, 60, null, null, null] },
  { key: "sdldl", name: "sdLDL", unit: "mg/dl", weight: 0.06, source: "Laboratorio", bandLimits: [null, null, 0, 5, 20, 30, 40, 50] },
  { key: "transaminasa_glutamico_oxalacetica_ast", name: "Transaminasa Glutamico Oxalacetica (AST)", unit: "U/l", weight: 0.02, source: "Laboratorio", bandLimits: [0, 5, 10, 15, 25, 35, 45, 50] },
  { key: "transaminasa_glutamico_piruvica_alt", name: "Transaminasa Glutamico Piruvica (ALT)", unit: "U/l", weight: 0.02, source: "Laboratorio", bandLimits: [0, 5, 10, 15, 25, 35, 45, 50] },
  { key: "trigliceridos", name: "Trigliceridos", unit: "mg/dl", weight: 0.03, source: "Laboratorio", bandLimits: [null, null, null, 30, 70, 100, 150, 175] },
  { key: "vldl", name: "VLDL", unit: "mg/dl", weight: 0.03, source: "Laboratorio", bandLimits: [0, 1, 2, 5, 15, 20, 30, 35] },
  { key: "vo2_estimado", name: "VO2 estimado", unit: "ml/kg/min", weight: 0.09, source: "Tests", bandLimits: [30, 36, 42, 50, 100, null, null, null] },
  { key: "hemoglobina", name: "Hemoglobina", unit: "g/dl", weight: 0.03, source: "Tests", bandLimits: [10.5, 10.6, 12, 13, 14.8, 15.5, 16.4, 16.4] },
  { key: "hematocrito", name: "Hematocrito", unit: "%", weight: 0.02, source: "Tests", bandLimits: [0.32, 0.321, 0.36, 0.38, 0.43, 0.45, 0.48, 0.481] },
  { key: "rdw_cv", name: "RDW - CV", unit: "%", weight: 0.04, source: "Tests", bandLimits: [0.03, 0.04, 0.05, 0.06, 0.125, 0.135, 0.145, 0.155] },
    ],
  },
  composicion_corporal: {
    domain_key: "composicion_corporal",
    domain_name_es: "Composici\u00f3n corporal",
    params: [
  { key: "grasa_corporal", name: "% grasa corporal", unit: "%", weight: 0.18, source: "Forms/Entrevista", bandLimits: [0.03, 0.07, 0.08, 0.1, 0.14, 0.18, 0.24, 0.35] },
  { key: "musculo_esqueletico", name: "% musculo esqueletico", unit: "%", weight: 0.19, source: "Forms/Entrevista", bandLimits: [0.2, 0.3, 0.35, 0.4, 0.6, 0.7, 0.75, 0.8] },
  { key: "edad_corporal", name: "Edad corporal", unit: "a\u00f1os", weight: 0.08, source: "Forms/Entrevista", bandLimits: [null, null, null, -15, -1, 0, 5, 10] },
  { key: "fuerza_de_agarre", name: "Fuerza de agarre", unit: "Kg", weight: 0.13, source: "Forms/Entrevista", bandLimits: [35, 40, 45, 50, 100, null, null, null] },
  { key: "grasa_visceral", name: "Grasa visceral", unit: "Unidad", weight: 0.1, source: "Forms/Entrevista", bandLimits: [0, 0, 0, 1, 2, 9, 12, 15] },
  { key: "pullups", name: "Pull-ups", unit: "cantidad", weight: 0.03, source: "Forms/Entrevista", bandLimits: [3, 6, 10, 15, 50, null, null, null] },
  { key: "pushups", name: "Push-ups", unit: "cantidad", weight: 0.03, source: "Tests", bandLimits: [15, 20, 30, 40, 100, null, null, null] },
  { key: "sentadilla_libre", name: "Sentadilla libre", unit: "Unidad", weight: 0.03, source: "Tests", bandLimits: [8, 10, 20, 30, 80, null, null, null] },
  { key: "test_de_equilibrio_en_un_pie", name: "Test de equilibrio en un pie", unit: "Seg", weight: 0.05, source: "Tests", bandLimits: [7, 10, 20, 30, 60, null, null, null] },
  { key: "vo2_max", name: "VO2 Max", unit: "ml/kg/min", weight: 0.18, source: "Tests", bandLimits: [30, 36, 42, 50, 100, null, null, null] },
    ],
  },
  habitos: {
    domain_key: "habitos",
    domain_name_es: "Habitos",
    params: [
  { key: "amalgamas_de_mercurio", name: "Amalgamas de mercurio", unit: "cantidad", weight: 0.04, source: "Forms/Entrevista", bandLimits: [null, null, null, -1, 0, 0, 1, 2] },
  { key: "ayuno_intermitente", name: "Ayuno intermitente", unit: "hr/dia", weight: 0.12, source: "Forms/Entrevista", bandLimits: [12, 13, 14, 16, 20, 23, null, null] },
  { key: "consistencia_en_ejercicio_semanal", name: "Consistencia en ejercicio semanal", unit: "veces/semana", weight: 0.1, source: "Forms/Entrevista", bandLimits: [1, 2, 3, 5, 8, 12, 18, 20] },
  { key: "consumo_de_alcohol_mensual", name: "Consumo de alcohol mensual", unit: "copas/mes", weight: 0.08, source: "Forms/Entrevista", bandLimits: [null, null, null, 0, 4, 6, 10, 16] },
  { key: "salud_de_encias", name: "Salud de encias", unit: "evento", weight: 0.1, source: "Forms/Entrevista", bandLimits: [null, null, null, -1, 0, 1, 2, 3] },
  { key: "uso_de_farmacos_cronicos", name: "Uso de farmacos cronicos", unit: "cantidad", weight: 0.08, source: "Forms/Entrevista", bandLimits: [null, null, null, -1, 0, 1, 2, 3] },
  { key: "ejercicio_semanal", name: "Ejercicio semanal", unit: "hr/semana", weight: 0.2, source: "Forms/Entrevista", bandLimits: [2, 4, 7, 10, 25, 28, 30, 32] },
  { key: "uso_de_pantallas_hrdia", name: "Uso de pantallas hr/dia", unit: "hr/dia", weight: 0.06, source: "Forms/Entrevista", bandLimits: [null, null, null, 0, 4, 6, 8, 10] },
  { key: "pasos_al_dia", name: "Pasos al d\u00eda", unit: "Pasos/dia", weight: 0.05, source: "Forms/Entrevista", bandLimits: [5000, 5500, 6500, 7800, 15000, 25000, null, null] },
  { key: "tabaquismo", name: "Tabaquismo", unit: "Cigarros/d\u00eda", weight: 0.08, source: "Forms/Entrevista", bandLimits: [null, null, null, -1, 0, 0, 1, 2] },
  { key: "respiracion_consciente", name: "Respiracion consciente", unit: "min/dia", weight: 0.04, source: "Forms/Entrevista", bandLimits: [2, 5, 8, 10, 90, 180, null, null] },
  { key: "minutos_de_luz_natural", name: "Minutos de luz natural", unit: "min/dia", weight: 0.05, source: "Forms/Entrevista", bandLimits: [2, 5, 10, 25, 90, 180, null, null] },
    ],
  },
  inflamacion: {
    domain_key: "inflamacion",
    domain_name_es: "Inflamaci\u00f3n",
    params: [
  { key: "acido_urico", name: "Acido urico", unit: "mg/dl", weight: 0.06, source: "Laboratorio", bandLimits: [2, 2.5, 3.1, 3.6, 5, 6, 7, 8] },
  { key: "factor_reumatoide", name: "Factor reumatoide", unit: "UI/ml", weight: 0.07, source: "Laboratorio", bandLimits: [null, null, 0, 1, 10, 15, 20, 25] },
  { key: "ferritina", name: "Ferritina", unit: "ng/ml", weight: 0.07, source: "Laboratorio", bandLimits: [12, 12.1, 20, 30, 90, 150, 200, 210] },
  { key: "ggt", name: "GGT", unit: "U/l", weight: 0.08, source: "Laboratorio", bandLimits: [5, 5.1, 10, 15, 30, 40, 59, 60] },
  { key: "homocisteina", name: "Homocisteina", unit: "mcmol/ml", weight: 0.15, source: "Laboratorio", bandLimits: [1, 2, 4, 5, 9, 12, 14, 17] },
  { key: "proteina_c_reactiva_cuantitativa_pcr", name: "Proteina C reactiva cuantitativa (PCR)", unit: "mg/dl", weight: 0.2, source: "Laboratorio", bandLimits: [null, null, null, 0, 0.2, 0.4, 0.6, 0.7] },
  { key: "tiempo_de_recuperacion_postejercicio", name: "Tiempo de recuperacion post-ejercicio", unit: "min", weight: 0.05, source: "Tests", bandLimits: [null, null, null, 1, 24, 36, 48, 50] },
  { key: "transaminasa_g_oxalacetica_ast_tgo", name: "Transaminasa G Oxalacetica AST (TGO)", unit: "U/l", weight: 0.03, source: "Laboratorio", bandLimits: [5, 5.1, 9, 15, 24, 35, 59, 60] },
  { key: "vitamina_d", name: "Vitamina D", unit: "ng/ml", weight: 0.13, source: "Laboratorio", bandLimits: [20, 30, 40, 50, 80, 90, 100, 105] },
  { key: "relacion_neutrofilos_linfocitos_nlr", name: "Relacion Neutrofilos / Linfocitos (NLR)", unit: "Ratio", weight: 0.11, source: "Calculo", bandLimits: [null, null, null, 0.1, 1.5, 2, 2.2, 2.5] },
  { key: "ldh", name: "LDH", unit: "Ratio", weight: 0.05, source: "Calculo", bandLimits: [null, null, null, 0.1, 1.5, 2, 2.2, 2.5] },
    ],
  },
  inmunidad: {
    domain_key: "inmunidad",
    domain_name_es: "Inmunidad",
    params: [
  { key: "antiestreptolisinas", name: "Antiestreptolisinas", unit: "UI/ml", weight: 0.11, source: "Laboratorio", bandLimits: [null, null, null, 0, 100, 200, 400, 500] },
  { key: "bilirrubina", name: "Bilirrubina", unit: "mg/dl", weight: 0.1, source: "Laboratorio", bandLimits: [null, null, null, 0.3, 1, 1.2, 1.5, 1.6] },
  { key: "iga", name: "IgA", unit: "mg/dl", weight: 0.08, source: "Laboratorio", bandLimits: [79, 80, 100, 120, 250, 300, 400, 401] },
  { key: "ige", name: "IgE", unit: "UI/ml", weight: 0.06, source: "Laboratorio", bandLimits: [null, null, null, 10, 40, 60, 100, 101] },
  { key: "igg", name: "IgG", unit: "mg/dl", weight: 0.1, source: "Laboratorio", bandLimits: [599, 600, 700, 800, 1200, 1300, 1400, 1401] },
  { key: "igm", name: "IgM", unit: "mg/dl", weight: 0.06, source: "Laboratorio", bandLimits: [39, 40, 60, 80, 150, 180, 220, 221] },
  { key: "indice_de_bilirrubina", name: "indice de bilirrubina", unit: "Ratio", weight: 0.06, source: "Laboratorio", bandLimits: [null, null, null, 0.05, 0.3, 0.5, 0.8, 0.9] },
  { key: "leucocitos_totales", name: "Leucocitos totales", unit: "/mcl", weight: 0.11, source: "Laboratorio", bandLimits: [2800, 3500, 4000, 4500, 6000, 7000, 8000, 10000] },
  { key: "proteina_c_reactiva_cuantitativa_pcr", name: "Proteina C reactiva cuantitativa (PCR)", unit: "mg/dl", weight: 0.08, source: "Laboratorio", bandLimits: [null, null, null, 0, 0.2, 0.4, 0.6, 0.7] },
  { key: "vitamina_d", name: "Vitamina D", unit: "ng/ml", weight: 0.08, source: "Laboratorio", bandLimits: [20, 30, 40, 50, 80, 90, 100, 110] },
  { key: "relacion_neutrofilos_linfocitos_nlr", name: "Relacion Neutrofilos / Linfocitos (NLR)", unit: "Ratio", weight: 0.11, source: "Calculo", bandLimits: [null, null, null, 0.1, 1.5, 2, 2.2, 2.5] },
  { key: "ldh", name: "LDH", unit: "Ratio", weight: 0.05, source: "Calculo", bandLimits: [5, 10, 15, 20, 200, 300, 400, 500] },
    ],
  },
  metabolismo: {
    domain_key: "metabolismo",
    domain_name_es: "Metabolismo",
    params: [
  { key: "flexibilidad_metabolica_subjetiva_puntuacion_de_test_ayuno", name: "Flexibilidad metabolica subjetiva (puntuacion de test ayuno)", unit: "score", weight: 0.06, source: "Tests", bandLimits: [40, 60, 80, 90, 100, null, null, null] },
  { key: "glucosa_en_ayuno", name: "Glucosa en ayuno", unit: "mg/dl", weight: 0.09, source: "Laboratorio", bandLimits: [25, 35, 45, 70, 85, 90, 99, 110] },
  { key: "glucosa_media_cgm", name: "Glucosa Media (CGM)", unit: "mg/dl", weight: 0.08, source: "Glucometro", bandLimits: [25, 35, 45, 70, 95, 105, 115, 120] },
  { key: "hba1c", name: "HbA1c %", unit: "%", weight: 0.14, source: "Laboratorio", bandLimits: [0.01, 0.025, 0.035, 0.049, 0.052, 0.056, 0.058, 0.06] },
  { key: "homair", name: "HOMA-IR", unit: "Ratio", weight: 0.11, source: "Laboratorio", bandLimits: [null, null, null, 0.1, 1, 1.5, 2, 3] },
  { key: "indice_aterogenico", name: "Indice Aterogenico", unit: "Ratio", weight: 0.05, source: "Laboratorio", bandLimits: [null, null, null, 0.1, 2.5, 3.5, 4.5, 6] },
  { key: "insulina", name: "Insulina", unit: "mgUI/ml", weight: 0.07, source: "Laboratorio", bandLimits: [null, null, null, 2, 6, 8, 10, 15] },
  { key: "moda_vs_media_cgm", name: "Moda VS Media (CGM)", unit: "Ratio", weight: 0.01, source: "Glucometro", bandLimits: [-16, -15, -10, -5, 5, 10, 15, 16] },
  { key: "numero_de_ingestas_al_dia", name: "Numero de ingestas al dia", unit: "cantidad", weight: 0.04, source: "Forms/Entrevista", bandLimits: [null, null, null, 1, 2, 3, 4, 5] },
  { key: "relacion_trigliceridos_hdl", name: "Relacion Trigliceridos / HDL", unit: "Ratio", weight: 0.07, source: "Calculo", bandLimits: [null, null, null, 0.1, 1.8, 2, 2.5, 2.8] },
  { key: "tiempo_en_rango_saludable_65150_cgm", name: "Tiempo en rango saludable [65-150] (CGM)", unit: "%", weight: 0.08, source: "Glucometro", bandLimits: [0.69, 0.7, 0.8, 0.9, 1, null, null, null] },
  { key: "trigliceridos", name: "Trigliceridos", unit: "mg/dl", weight: 0.04, source: "Laboratorio", bandLimits: [null, null, null, 30, 70, 100, 150, 175] },
  { key: "variabilidad_glucemica_cgm_sd", name: "Variabilidad glucemica (CGM) (SD)", unit: "score", weight: 0.03, source: "Glucometro", bandLimits: [null, null, null, 0, 15, 20, 25, 26] },
  { key: "ggt", name: "GGT", unit: "U/l", weight: 0.04, source: "Laboratorio", bandLimits: [5, 5.1, 10, 15, 30, 40, 59, 60] },
  { key: "transaminasa_glutamico_piruvica_alt", name: "Transaminasa Glutamico Piruvica (ALT)", unit: "U/l", weight: 0.04, source: "Laboratorio", bandLimits: [5, 5.1, 10, 15, 24, 35, 49, 50] },
    ],
  },
  renal_y_micronutrientes: {
    domain_key: "renal_y_micronutrientes",
    domain_name_es: "Renal y Micronutrientes",
    params: [
  { key: "acido_urico", name: "acido urico", unit: "mg/dl", weight: 0.1, source: "Laboratorio", bandLimits: [2, 2.5, 3.1, 3.6, 5, 6, 7, 8] },
  { key: "capacidad_de_fijacion_de_hierro", name: "Capacidad de fijacion de hierro", unit: "mcg/dl", weight: 0.05, source: "Laboratorio", bandLimits: [150, 200, 220, 250, 400, 450, 500, 550] },
  { key: "cloro", name: "Cloro", unit: "mE1/L", weight: 0.04, source: "Laboratorio", bandLimits: [93, 95, 98, 100, 106, 108, 110, 115] },
  { key: "creatinina_serica", name: "Creatinina Serica", unit: "mg/dl", weight: 0.08, source: "Laboratorio", bandLimits: [null, null, 0.7, 0.8, 1.1, 1.2, 1.3, 1.4] },
  { key: "ferritina", name: "Ferritina", unit: "ng/ml", weight: 0.08, source: "Laboratorio", bandLimits: [5, 10, 20, 50, 150, 200, 300, 400] },
  { key: "folato_acido_folico", name: "Folato (acido folico)", unit: "ng/ml", weight: 0.06, source: "Laboratorio", bandLimits: [5.5, 6, 8, 10, 18, 20, 24, 25] },
  { key: "hierro_libre", name: "Hierro Libre", unit: "mcg/dl", weight: 0.02, source: "Laboratorio", bandLimits: [null, null, 0, 0.1, 1, 2, 3, 3.5] },
  { key: "hierro_serico", name: "Hierro serico", unit: "mcg/dl", weight: 0.03, source: "Laboratorio", bandLimits: [50, 60, 70, 80, 140, 160, 180, 190] },
  { key: "magnesio", name: "Magnesio", unit: "mg/dl", weight: 0.07, source: "Laboratorio", bandLimits: [1.6, 1.8, 2, 2.2, 2.6, 2.8, 3.2, 3.3] },
  { key: "nitrogeno_ureico_bun", name: "Nitrogeno ureico (BUN)", unit: "mg/dl", weight: 0.04, source: "Laboratorio", bandLimits: [null, null, 5, 10, 18, 20, 25, 30] },
  { key: "potasio", name: "Potasio", unit: "mE1/L", weight: 0.05, source: "Laboratorio", bandLimits: [3.3, 3.5, 3.8, 4, 4.5, 5, 5.5, 6] },
  { key: "relacion_buncreatinina", name: "Relacion BUN/Creatinina", unit: "Ratio", weight: 0.05, source: "Laboratorio", bandLimits: [null, null, null, 10, 16, 20, 25, 27] },
  { key: "saturacion_de_hierro", name: "Saturacion de hierro", unit: "%", weight: 0.04, source: "Laboratorio", bandLimits: [15, 18, 20, 25, 40, 42, 45, 50] },
  { key: "sodio", name: "Sodio", unit: "mE1/L", weight: 0.04, source: "Laboratorio", bandLimits: [125, 130, 135, 138, 142, 145, 150, 160] },
  { key: "transferrina", name: "Transferrina", unit: "mg/dl", weight: 0.03, source: "Laboratorio", bandLimits: [180, 200, 220, 250, 350, 380, 400, 450] },
  { key: "urea", name: "Urea", unit: "mg/dl", weight: 0.02, source: "Laboratorio", bandLimits: [null, null, null, 15, 30, 40, 50, 55] },
  { key: "vitamina_b12", name: "Vitamina B12", unit: "pg/ml", weight: 0.05, source: "Laboratorio", bandLimits: [350, 400, 450, 500, 900, 1000, 1200, 1500] },
  { key: "vitamina_d", name: "Vitamina D", unit: "ng/ml", weight: 0.05, source: "Laboratorio", bandLimits: [20, 30, 40, 50, 90, 100, 105, 110] },
  { key: "de_agua_corporal", name: "% de agua corporal", unit: "%", weight: 0.05, source: "Laboratorio", bandLimits: [0.45, 0.49, 0.55, 0.6, 0.69, 0.72, 0.74, 0.75] },
  { key: "calciofosforo", name: "Calcio*Fosforo", unit: "mg2/dl2", weight: 0.05, source: "Laboratorio", bandLimits: [20, 21, 25, 30, 45, 50, null, 65] },
    ],
  },
  sistema_hormonal: {
    domain_key: "sistema_hormonal",
    domain_name_es: "Sistema hormonal",
    params: [
  { key: "anticuerpos_antitiroglobulina", name: "Anticuerpos Anti-Tiroglobulina", unit: "UI/ml", weight: 0.07, source: "Laboratorio", bandLimits: [null, null, null, 0, 5, 10, 15, 20] },
  { key: "anticuerpos_antitpo", name: "Anticuerpos Anti-TPO", unit: "UI/ml", weight: 0.07, source: "Laboratorio", bandLimits: [null, null, null, 0, 10, 20, 30, 35] },
  { key: "cortisol_matutino", name: "Cortisol matutino", unit: "mcg/dl", weight: 0.12, source: "Laboratorio", bandLimits: [5, 6, 8, 10, 15, 17, 18, 20] },
  { key: "fsh", name: "FSH", unit: "mUI/ml", weight: 0.1, source: "Laboratorio", bandLimits: [1, 1.1, 1.9, 3.1, 7.2, 8.4, 9.2, 9.3] },
  { key: "lh", name: "LH", unit: "mUI/ml", weight: 0.06, source: "Laboratorio", bandLimits: [0.5, 0.6, 2.2, 4.5, 12.4, 14.7, 16.3, 16.4] },
  { key: "prolactina", name: "Prolactina", unit: "ng/ml", weight: 0.05, source: "Laboratorio", bandLimits: [3, 3.1, 5, 10, 20, 25, 40, 41] },
  { key: "t3_libre", name: "T3 libre", unit: "ng/dl", weight: 0.1, source: "Laboratorio", bandLimits: [2.2, 2.5, 2.8, 3.2, 4.2, null, null, null] },
  { key: "estradiol", name: "Estradiol", unit: "pg/ml", weight: 0.15, source: "Laboratorio", bandLimits: [30, 31, 72, 128, 345, 408, 450, 451] },
  { key: "testosterona_total", name: "Testosterona total", unit: "ng/ml", weight: 0.05, source: "Laboratorio", bandLimits: [0.1, 0.11, 0.15, 0.2, 0.55, 0.7, 0.9, 0.91] },
  { key: "tsh", name: "TSH", unit: "mcU/ml", weight: 0.15, source: "Laboratorio", bandLimits: [0.1, 0.2, 0.3, 0.5, 2, 2.5, 3, 3.5] },
  { key: "progesterona", name: "Progesterona", unit: "ng/ml", weight: 0.08, source: "Laboratorio", bandLimits: [1.9, 2, 4.3, 7.8, 19.2, 22.7, 25, 25.1] },
    ],
  },
  sueno: {
    domain_key: "sueno",
    domain_name_es: "Sue\u00f1o",
    params: [
  { key: "consistencia_de_horario", name: "Consistencia de horario", unit: "min", weight: 0.2, source: "Forms/Entrevista", bandLimits: [null, null, null, 0, 45, 75, null, 90] },
  { key: "cortisol_matutino", name: "Cortisol matutino", unit: "mcg/dl", weight: 0.1, source: "Laboratorio", bandLimits: [4, 5, 6, 10, 15, 18, 20, 25] },
  { key: "duracion_promedio", name: "Duracion promedio", unit: "hrs", weight: 0.1, source: "Forms/Entrevista", bandLimits: [6, 6, 7, 7.5, 8.5, 9, 9.5, 10] },
  { key: "edad_corporal", name: "Edad corporal", unit: "diferencia de a\u00f1os", weight: 0.05, source: "Forms/Entrevista", bandLimits: [0, 0, 0, -10, -1, 0, 5, 10] },
  { key: "eficiencia_del_sueno", name: "Eficiencia del sueno", unit: "score", weight: 0.08, source: "Wearable", bandLimits: [75, 75, 80, 85, 100, null, null, null] },
  { key: "energia_al_despertar", name: "Energia al despertar", unit: "score", weight: 0.1, source: "Forms/Entrevista", bandLimits: [6, 6, 7, 9, 10, null, null, null] },
  { key: "exposicion_solar_matutina", name: "Exposicion solar matutina", unit: "min", weight: 0.1, source: "Forms/Entrevista", bandLimits: [5, 5, 15, 20, 45, null, null, null] },
  { key: "sueno_deep", name: "Sueno DEEP%", unit: "%", weight: 0.1, source: "Wearable", bandLimits: [12, 12, 15, 20, 25, null, null, null] },
  { key: "sueno_rem", name: "Sueno REM%", unit: "%", weight: 0.1, source: "Wearable", bandLimits: [15, 15, 18, 22, 27, null, null, null] },
  { key: "testosterona_total", name: "Testosterona total", unit: "ng/dl", weight: 0.07, source: "Laboratorio", bandLimits: [3, 4, 5, 7, 13, 15, 20, 25] },
    ],
  },
  vitalidad: {
    domain_key: "vitalidad",
    domain_name_es: "Vitalidad",
    params: [
  { key: "claridad_mental", name: "Claridad mental", unit: "score", weight: 0.08, source: "Forms/Entrevista", bandLimits: [5, 6, 8, 9, 10, null, null, null] },
  { key: "cortisol_matutino", name: "Cortisol matutino", unit: "mcg/dl", weight: 0.09, source: "Laboratorio", bandLimits: [5, 6, 8, 10, 15, 17, 18, 20] },
  { key: "cpk", name: "CPK", unit: "U/L", weight: 0.05, source: "Laboratorio", bandLimits: [0, 0, 25, 50, 200, 300, 500, 550] },
  { key: "edad_corporal", name: "Edad corporal", unit: "diferencia de a\u00f1os", weight: 0.06, source: "Forms/Entrevista", bandLimits: [null, null, null, -10, -1, 0, 5, 10] },
  { key: "energia_diaria", name: "Energia diaria", unit: "score", weight: 0.12, source: "Forms/Entrevista", bandLimits: [5, 6, 8, 9, 10, null, null, null] },
  { key: "fuerza_de_agarre", name: "Fuerza de agarre", unit: "kg", weight: 0.12, source: "Forms/Entrevista", bandLimits: [20, 30, 40, 50, 100, null, null, null] },
  { key: "motivacion_y_entusiasmo", name: "Motivacion y entusiasmo", unit: "score", weight: 0.05, source: "Forms/Entrevista", bandLimits: [5, 6, 8, 9, 10, null, null, null] },
  { key: "musculo_esqueletico", name: "Musculo esqueletico %", unit: "%", weight: 0.09, source: "Forms/Entrevista", bandLimits: [0.25, 0.3, 0.35, 0.4, 0.65, null, null, null] },
  { key: "resiliencia_emocional_estres", name: "Resiliencia emocional / estres", unit: "score", weight: 0.05, source: "Forms/Entrevista", bandLimits: [5, 6, 8, 9, 10, null, null, null] },
  { key: "senales_de_fatiga_cronica", name: "Se\u00f1ales de fatiga cronica", unit: "score", weight: 0.03, source: "Forms/Entrevista", bandLimits: [null, null, null, 0, 2, 4, 6, 7] },
  { key: "testosterona_libre", name: "Testosterona libre", unit: "pg/ml", weight: 0.07, source: "Laboratorio", bandLimits: [20, 22, 25, 30, 45, 60, null, null] },
  { key: "vitamina_b12", name: "Vitamina B12", unit: "pg/ml", weight: 0.06, source: "Laboratorio", bandLimits: [350, 400, 500, 600, 900, 1000, 1200, 1500] },
  { key: "vitamina_d", name: "Vitamina D", unit: "ng/ml", weight: 0.08, source: "Laboratorio", bandLimits: [20, 30, 40, 50, 80, 90, 100, 110] },
  { key: "magnesio", name: "Magnesio", unit: "mg/dl", weight: 0.05, source: "Laboratorio", bandLimits: [1.6, 1.8, 2, 2.2, 2.6, 2.8, 3.2, 3.3] },
    ],
  },
};

// Total: HOMBRES 138 params · MUJERES 138 params
