/**
 * Catálogo de Intervenciones ATP — fuente de verdad curada (constants, git-versionado).
 *
 * Doctrina (scope 2026-07-11 + decisiones aprobadas + review v3 Enrique 2026-07-11):
 *  - En ATP NO se recomiendan suplementos ni fármacos. Las intervenciones son
 *    hábitos / prácticas / rituales / técnicas de medicina y nutrición funcional.
 *  - El motor cruza las `roots` de cada intervención contra las raíces del DX del
 *    user y sugiere con semáforo. El user activa libremente (sin límite).
 *  - Cada MODALIDAD es una intervención distinta (comparten filosofía, no
 *    implementación): "Ayuno 16:8" ≠ "Ayuno 18:6". Se enlazan con `family`.
 *  - El user puede crear intervenciones CUSTOM (no viven aquí; viven en
 *    user_interventions.custom_definition).
 *  - Los recordatorios circadianos (dormir/comer) leen de agenda del user
 *    (cronotipo = ajuste inicial, user manda final vía agenda). Delfín NO es
 *    cronotipo — es estado transitorio a sanar hacia León/Oso/Lobo.
 *
 * ✅ v3 CURADO ENRIQUE 2026-07-11: 59+ intervenciones aprobadas. Fuente:
 *  `Business development/Beta_Launch_Kit/09b_SEEDS_CATALOGO_ARRANQUE_MARIANA.md`
 *
 * ⏳ PENDIENTE 2da sesión Mariana: validar ajustes v3 + agregar ciclo femenino,
 * tiroides, postparto, salud masculina, piel, immune post-infección.
 *
 * ⚠️ REQUIEREN VALIDACIÓN CLÍNICA MARIANA (campo `requiresClinicalValidation: true`;
 * Mariana quita el flag al firmar cada una — task #9). El motor NO las sugiere
 * (matchInterventions las excluye de suggestions/universals); el user sí puede
 * activarlas manualmente si ya las tiene en user_interventions. Flaggeadas hoy:
 *  bulletproof_coffee (Cowork corregido: doctrina Enrique BPC no sube insulina),
 *  wim_hof_basico, wim_hof_extendido, hiperventilacion_matutina, tabla_co2,
 *  tabla_o2, luz_roja_ojos, dive_reflex_cara_hielo, jawzercise, ayuno_20_4_omad,
 *  ejercicio_ayuno_fuerza, protocolo_ayuno_sardinas.
 */
import type { InterventionCategory, InterventionRoot } from './intervention-vocab';

export type Priority = 1 | 2 | 3; // 1 🔴 P1 · 2 🟡 P2 · 3 🟢 P3 (default; el motor re-prioriza)
export type TimeOfDay = 'morning' | 'noon' | 'afternoon' | 'evening' | 'night';
export type EvidenceLevel = 'N1' | 'N2' | 'N3' | 'N4';

export interface Intervention {
  /** Key estable, snake_case. Referenciado por user_interventions.intervention_key. */
  key: string;
  /** Nombre corto que ve el user (≤50 chars). */
  name: string;
  /** Cómo se hace — 1 línea accionable. */
  how: string;
  /** Beneficio — por qué funciona (1-2 líneas). */
  benefit: string;
  /** Categorías (para qué sirve) — múltiples. */
  categories: InterventionCategory[];
  /** Raíces que ataca — múltiples. [] para universales fijas sin raíz específica. */
  roots: InterventionRoot[];
  /** Regla clínica en lenguaje normal ("cuándo asignarla"). */
  assignRule: string;
  /** Prioridad default 🔴🟡🟢. */
  priority: Priority;
  /** Familia de modalidades (p.ej. 'ayuno'); las modalidades comparten familia. */
  family?: string;
  /** Universal: fallback garantizado / circadiano. */
  isUniversal?: boolean;
  /** Universal circadiano: el timing se calcula desde user_chronotype (no fijo). */
  circadian?: 'sleep' | 'eat';
  /** Momento del día sugerido (para timing e íconos). */
  timeOfDay?: TimeOfDay;
  /** Info científica / bibliografía / "considerar consultar con tu nutriólogo". */
  scientificInfo?: string;
  /** Nivel de evidencia (jerarquía ARGOS). */
  evidenceLevel?: EvidenceLevel;
  /** ⚠️ Requiere validación clínica adicional de Mariana antes de activar producción. */
  requiresClinicalValidation?: boolean;
}

export const INTERVENTIONS_CATALOG: Intervention[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // UNIVERSALES P1 · fallback garantizado (7 confirmados Enrique v3)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    key: 'hidratacion_matutina',
    name: 'Hidratación matutina 500 ml',
    how: 'Bebe 500 ml de agua natural al despertar (opcional pizca de sal de mar), antes de café o comida.',
    benefit: 'Rehidrata tras el ayuno nocturno, activa peristalsis y moviliza cortisol matutino sano.',
    categories: ['hidratacion', 'digestion', 'circadiano', 'energia'],
    roots: ['cortisol_matutino_bajo', 'ritmo_circadiano_desregulado', 'digestion_estres_autonomico'],
    assignRule: 'Universal — todos.',
    priority: 1,
    isUniversal: true,
    timeOfDay: 'morning',
  },
  {
    key: 'exposicion_solar_matutina',
    name: 'Exposición solar matutina (Fitzpatrick)',
    how: 'Sal a luz solar directa entre 7-9am, ojos abiertos sin lentes de sol. Minutos según tu fototipo: I: 5 min · II-III: 10 min · IV-V: 15-20 min · VI: 20-30 min.',
    benefit: 'Ancla ritmo circadiano, dispara cortisol matutino sano, mejora conversión melatonina 14h después, sube serotonina y sintetiza vitamina D.',
    categories: ['sueno', 'circadiano', 'hormonal', 'cognitivo', 'energia', 'piel'],
    roots: ['cortisol_matutino_bajo', 'ritmo_circadiano_desregulado', 'deficit_exposicion_solar', 'deficit_sueno_profundo'],
    assignRule: 'Universal — dosis adaptada por fototipo Fitzpatrick. Reforzar en insomnio de conciliación, fatiga matutina, tristeza estacional o vitamina D baja.',
    priority: 1,
    isUniversal: true,
    timeOfDay: 'morning',
    evidenceLevel: 'N2',
  },
  {
    key: 'recordatorio_dormir',
    name: 'Hora de dormir',
    how: 'Notificación 60 min antes de tu hora de dormir en agenda. Prepara ambiente, termina pantallas, baja intensidad.',
    benefit: 'Ancla horario de sueño consistente, respeta tu ritmo real, mejora sueño profundo y alinea circadiano.',
    categories: ['sueno', 'circadiano', 'ritual'],
    roots: ['ritmo_circadiano_desregulado', 'deficit_sueno_profundo'],
    assignRule: 'Universal — timing tomado de agenda del user (inicializado por cronotipo León/Oso/Lobo). Delfín = estado transitorio, converger al cronotipo madre.',
    priority: 1,
    isUniversal: true,
    circadian: 'sleep',
  },
  {
    key: 'recordatorio_comer',
    name: 'Ventana de alimentación',
    how: 'Notificaciones inicio y cierre de ventana de comida configurada en agenda del user.',
    benefit: 'Estructura horario de comidas coherente con ritmo real del user, mejora regulación metabólica.',
    categories: ['metabolismo', 'circadiano', 'digestion', 'ritual'],
    roots: ['ritmo_circadiano_desregulado', 'hiperinsulinemia', 'digestion_estres_autonomico'],
    assignRule: 'Universal — horario de agenda del user (inicial por cronotipo + ayuno preferido, ajustable). Delfín NO es cronotipo.',
    priority: 1,
    isUniversal: true,
    circadian: 'eat',
  },
  {
    key: 'apagar_pantallas_noche',
    name: 'Pantallas off 30 min antes de dormir',
    how: 'Corta pantallas (o modo cálido/rojo) mínimo 30 min antes de tu hora de dormir. Iluminación tenue cálida en casa.',
    benefit: 'Melatonina no se suprime, se acelera onset del sueño y mejora arquitectura de sueño profundo.',
    categories: ['sueno', 'circadiano', 'cognitivo'],
    roots: ['sobreexposicion_luz_azul', 'ritmo_circadiano_desregulado', 'deficit_sueno_profundo'],
    assignRule: 'Universal (versión mínima). Reforzar 60/90 min si insomnio, sueño no reparador, tono nocturno elevado.',
    priority: 1,
    isUniversal: true,
    timeOfDay: 'night',
    family: 'pantallas_off',
  },
  {
    key: 'grounding_earthing',
    name: 'Grounding 10-15 min',
    how: 'Contacto directo de pies descalzos con tierra, pasto o arena 10-15 min. Idealmente combinado con exposición solar matutina.',
    benefit: 'Reduce carga inflamatoria, mejora HRV, ancla circadiano por contacto con Schumann, meditativo.',
    categories: ['inflamacion', 'circadiano', 'estres', 'ritual', 'cardiovascular'],
    roots: ['inflamacion_silenciosa', 'estres_cronico', 'ritmo_circadiano_desregulado'],
    assignRule: 'Universal — reforzar en inflamación silenciosa y estrés crónico.',
    priority: 1,
    isUniversal: true,
    family: 'grounding',
    evidenceLevel: 'N3',
  },
  {
    key: 'respiracion_nocturna',
    name: 'Respiración nocturna en cama',
    how: 'Respiración 4-7-8 o physiological sigh durante 5 min antes de dormir (4 ciclos de 4-7-8 o 30 respiraciones diafragmáticas lentas).',
    benefit: 'Activa parasimpático, baja frecuencia cardíaca, facilita transición a sueño profundo y reduce ansiedad rumiativa.',
    categories: ['sueno', 'ansiedad', 'estres', 'ritual', 'cardiovascular'],
    roots: ['adrenalina_nocturna', 'estres_cronico', 'cortisol_elevado_sostenido', 'deficit_sueno_profundo'],
    assignRule: 'Universal — reforzar en insomnio de conciliación y adrenalina nocturna.',
    priority: 1,
    isUniversal: true,
    timeOfDay: 'night',
    family: 'respiracion_nocturna',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SUEÑO / CIRCADIANO
  // ═══════════════════════════════════════════════════════════════════════════

  {
    key: 'cerrar_comida_3h_antes_dormir',
    name: 'Cerrar comida 3h antes de dormir',
    how: 'Termina última comida sólida 3h antes de tu hora de dormir habitual (ajustado a cronotipo).',
    benefit: 'Melatonina no compite con digestión, mejora sueño profundo, reduce reflujo, permite reparación nocturna.',
    categories: ['sueno', 'digestion', 'metabolismo', 'circadiano', 'inflamacion'],
    roots: ['deficit_sueno_profundo', 'reflujo_funcional', 'ritmo_circadiano_desregulado', 'hiperinsulinemia', 'sobrecarga_hepatica'],
    assignRule: 'Universal recomendado. Flag P1 si reflujo, insomnio de mantenimiento o hiperinsulinemia.',
    priority: 2,
    timeOfDay: 'evening',
  },
  {
    key: 'pantallas_off_60min',
    name: 'Pantallas off 60 min antes de dormir',
    how: 'Corta pantallas (o modo cálido/rojo) 60 min antes de dormir.',
    benefit: 'Mayor protección de melatonina que la versión mínima 30 min.',
    categories: ['sueno', 'circadiano', 'cognitivo'],
    roots: ['sobreexposicion_luz_azul', 'ritmo_circadiano_desregulado', 'deficit_sueno_profundo', 'adrenalina_nocturna'],
    assignRule: 'Insomnio, sueño no reparador o exposición nocturna elevada.',
    priority: 2,
    family: 'pantallas_off',
    timeOfDay: 'night',
  },
  {
    key: 'pantallas_off_90min',
    name: 'Pantallas off 90 min antes de dormir',
    how: 'Corta pantallas (o modo cálido/rojo) 90 min antes de dormir. Iluminación tenue cálida en casa.',
    benefit: 'Versión completa recomendada — máxima protección de melatonina y arquitectura de sueño.',
    categories: ['sueno', 'circadiano', 'cognitivo'],
    roots: ['sobreexposicion_luz_azul', 'ritmo_circadiano_desregulado', 'deficit_sueno_profundo', 'adrenalina_nocturna'],
    assignRule: 'Insomnio persistente, sueño no reparador crónico, adrenalina nocturna documentada.',
    priority: 2,
    family: 'pantallas_off',
    timeOfDay: 'night',
  },
  {
    key: 'blackout_total_cuarto',
    name: 'Blackout total del cuarto',
    how: 'Elimina TODA luz artificial del cuarto de dormir: cortinas blackout, tapar LEDs, cero pantallas encendidas.',
    benefit: 'Melatonina óptima, sueño profundo aumenta 20-30%, mejora reparación glinfática.',
    categories: ['sueno', 'circadiano'],
    roots: ['sobreexposicion_luz_azul', 'deficit_sueno_profundo', 'ritmo_circadiano_desregulado'],
    assignRule: 'Universal recomendado. Flag P1 si sueño no reparador o cuarto con contaminación lumínica.',
    priority: 2,
  },
  {
    key: 'antifaz_nocturno',
    name: 'Antifaz nocturno',
    how: 'Antifaz oscuro cómodo si no puedes lograr blackout total (viajes, cuarto compartido).',
    benefit: 'Simula blackout, protege melatonina, portable.',
    categories: ['sueno', 'circadiano', 'ritual'],
    roots: ['sobreexposicion_luz_azul', 'deficit_sueno_profundo', 'ritmo_circadiano_desregulado'],
    assignRule: 'Cuarto sin blackout, viajero frecuente, turnista.',
    priority: 2,
    timeOfDay: 'night',
  },
  {
    key: 'temperatura_cuarto_frio',
    name: 'Cuarto a 16-19°C',
    how: 'Cuarto de dormir a 16-19°C (60-67°F). AC, ventilador o abrir ventana según clima.',
    benefit: 'Caída de temperatura corporal facilita onset y profundidad de sueño.',
    categories: ['sueno', 'circadiano'],
    roots: ['deficit_sueno_profundo', 'ritmo_circadiano_desregulado'],
    assignRule: 'Universal — bajo umbral de implementación.',
    priority: 2,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // AYUNO + METABOLISMO
  // ═══════════════════════════════════════════════════════════════════════════

  {
    key: 'ayuno_14_10',
    name: 'Ayuno 14:10 (suave)',
    how: 'Ventana de comida 10h. Ayuno 14h con agua, té sin endulzar o café solo.',
    benefit: 'Beneficio metabólico con menor estrés hormonal que ventanas más agresivas.',
    categories: ['metabolismo', 'hormonal'],
    roots: ['hiperinsulinemia', 'resistencia_insulina'],
    assignRule: 'Primer acercamiento al ayuno, mujeres en fase folicular, hipoglucemia reactiva.',
    priority: 2,
    family: 'ayuno',
    scientificInfo: 'Considerar consultar con tu nutriólogo antes de iniciar.',
  },
  {
    key: 'ayuno_16_8',
    name: 'Ayuno 16:8 con carbos densos en cena',
    how: 'Ventana de comida 12:00-20:00. Cena con carbos densos (papa, camote, arroz) 3h antes de dormir.',
    benefit: 'Regula insulina diurna, activa autofagia y mejora sueño profundo (serotonina→melatonina de carbos nocturnos).',
    categories: ['metabolismo', 'sueno', 'hormonal', 'inflamacion'],
    roots: ['hiperinsulinemia', 'resistencia_insulina', 'sobrecarga_hepatica', 'inflamacion_silenciosa'],
    assignRule: 'Adulto con signos de resistencia a la insulina, HOMA-IR elevado, cortisol matutino OK, sin TCA previos.',
    priority: 2,
    family: 'ayuno',
    scientificInfo: 'Considerar consultar con tu nutriólogo antes de iniciar.',
    evidenceLevel: 'N2',
  },
  {
    key: 'ayuno_18_6',
    name: 'Ayuno 18:6 (agresivo)',
    how: 'Ventana de comida de 6h. Versión más agresiva.',
    benefit: 'Mayor presión sobre sensibilidad a la insulina en perfiles que ya toleran 16:8.',
    categories: ['metabolismo', 'inflamacion'],
    roots: ['hiperinsulinemia', 'resistencia_insulina'],
    assignRule: 'Hombres con resistencia establecida que ya toleran 16:8; nunca con TCA previos.',
    priority: 3,
    family: 'ayuno',
    scientificInfo: 'Considerar consultar con tu nutriólogo antes de iniciar.',
  },
  {
    key: 'ayuno_20_4_omad',
    name: 'Ayuno 20:4 / OMAD',
    how: 'Ventana de comida de 4h (una comida al día). Solo con supervisión clínica.',
    benefit: 'Máxima presión metabólica y autofagia sostenida.',
    categories: ['metabolismo', 'inflamacion'],
    roots: ['hiperinsulinemia', 'resistencia_insulina'],
    assignRule: 'Solo con supervisión clínica. Adulto muy avanzado en ayuno.',
    priority: 3,
    family: 'ayuno',
    scientificInfo: 'Requiere supervisión clínica activa. Considerar consultar con tu nutriólogo.',
    requiresClinicalValidation: true,
  },
  {
    key: 'caminata_postprandial',
    name: 'Caminata post-comida 10 min',
    how: 'Camina suave 10 min inmediatamente después de comida principal (dentro de los 20 min post-comida).',
    benefit: 'Reduce glucosa postprandial ~20-30%, mejora vaciamiento gástrico y activa músculo como sink de glucosa.',
    categories: ['metabolismo', 'digestion', 'movimiento', 'cardiovascular'],
    roots: ['hiperinsulinemia', 'resistencia_insulina', 'reflujo_funcional', 'sedentarismo'],
    assignRule: 'Adulto con glucosa postprandial elevada, HOMA-IR alto, resistencia, reflujo o síndrome metabólico.',
    priority: 2,
  },
  {
    key: 'bulletproof_coffee',
    name: 'Bulletproof coffee',
    how: 'Café solo + 15g MCT oil + 10g mantequilla de vaca de pastoreo, blendeado.',
    benefit: 'Cetosis suave, energía sostenida, apetito reducido. NO sube insulina significativamente. Respeta ayuno metabólico (rompe solo el ayuno profundo). Saciante → baja consumo de carbos → puede reducir triglicéridos.',
    categories: ['metabolismo', 'energia', 'nutricion'],
    roots: ['hiperinsulinemia', 'sobrecarga_procesados', 'cortisol_matutino_bajo'],
    assignRule: 'Persona buscando saciedad matutina, extensión de ayuno metabólico, low-carb / cetogénico. Contraindicación clara: NO combinar con dieta alta en carbos (>20% cal o >100g/día).',
    priority: 2,
    timeOfDay: 'morning',
    scientificInfo: 'Doctrina Enrique 2026-07-11 (Cowork corregido): TG suben por carbohidratos no por grasa dietética. Flag correcto es dieta alta en carbos, no perfil lipídico.',
    requiresClinicalValidation: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DIGESTIÓN
  // ═══════════════════════════════════════════════════════════════════════════

  {
    key: 'masticar_mas_20',
    name: 'Masticar >20 veces por bocado',
    how: 'Cuenta más de 20 masticadas por bocado hasta que la comida sea prácticamente líquida antes de tragar.',
    benefit: 'Activa fase cefálica digestiva, produce enzimas salivales, mejora absorción y reduce carga sobre estómago e intestino.',
    categories: ['digestion', 'ritual'],
    roots: ['disbiosis', 'digestion_estres_autonomico', 'reflujo_funcional', 'permeabilidad_intestinal'],
    assignRule: 'Distensión postprandial, gases, reflujo, SIBO sospechado o digestión errática.',
    priority: 2,
  },
  {
    key: 'agua_fuera_comidas',
    name: 'Agua fuera de las comidas',
    how: 'No tomar líquidos 20 min antes ni 30-60 min después de las comidas. Sorbos pequeños durante si necesario.',
    benefit: 'Preserva HCl gástrico y enzimas, mejora absorción y reduce distensión.',
    categories: ['digestion', 'hidratacion', 'ritual'],
    roots: ['digestion_estres_autonomico', 'reflujo_funcional', 'disbiosis'],
    assignRule: 'Reflujo, distensión postprandial, digestión débil o deficiencia de HCl sospechada.',
    priority: 3,
  },
  {
    key: 'oil_pulling_coco',
    name: 'Oil pulling con aceite de coco',
    how: '15-20ml de aceite de coco, enjuagar 10-15 min en boca (sin tragar), escupir en basura.',
    benefit: 'Reduce carga bacteriana bucal, mejora salud gingival, "detox" oral tradicional.',
    categories: ['digestion', 'inmunologico', 'ritual'],
    roots: ['disbiosis', 'inflamacion_silenciosa'],
    assignRule: 'Halitosis, gingivitis, disbiosis o caries recurrentes. Puede ser diario.',
    priority: 3,
    family: 'oil_pulling',
    timeOfDay: 'morning',
  },
  {
    key: 'oil_pulling_oregano',
    name: 'Oil pulling con aceite de coco + orégano',
    how: '15-20ml de aceite de coco + 1 gota (SOLO 1) de aceite esencial de orégano (muy fuerte). Revolver bien antes de meter en boca, enjuagar 10-15 min.',
    benefit: 'Más antimicrobiano que aceite solo por acción del orégano.',
    categories: ['digestion', 'inmunologico', 'ritual'],
    roots: ['disbiosis', 'inflamacion_silenciosa'],
    assignRule: 'Disbiosis moderada-severa. Ciclado 4 días on / 3 días off (no diario por potencia del orégano).',
    priority: 3,
    family: 'oil_pulling',
    timeOfDay: 'morning',
  },
  {
    key: 'postura_cuclillas_defecar',
    name: 'Postura en cuclillas al defecar',
    how: 'Eleva pies con banco (tipo Squatty Potty) al defecar, cadera flexionada, columna neutra.',
    benefit: 'Ángulo anorrectal óptimo, elimina Valsalva, previene hemorroides y mejora vaciamiento completo.',
    categories: ['digestion', 'ritual'],
    roots: ['digestion_estres_autonomico', 'reflujo_funcional'],
    assignRule: 'Universal recomendado. Flag P1 si constipación, hemorroides o evacuación incompleta.',
    priority: 3,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // RESPIRACIÓN + BREATHWORK
  // ═══════════════════════════════════════════════════════════════════════════

  {
    key: 'respiracion_478',
    name: 'Respiración 4-7-8 pre-sueño',
    how: 'Inhalar 4 seg por nariz, retener 7 seg, exhalar 8 seg por boca. 4 ciclos completos, en cama antes de dormir.',
    benefit: 'Activa parasimpático, baja frecuencia cardíaca, facilita transición a sueño profundo, reduce rumiación.',
    categories: ['sueno', 'ansiedad', 'estres', 'ritual', 'cardiovascular'],
    roots: ['adrenalina_nocturna', 'estres_cronico', 'cortisol_elevado_sostenido', 'deficit_sueno_profundo'],
    assignRule: 'Insomnio de conciliación, ansiedad nocturna, rumiación, pulso elevado en cama.',
    priority: 2,
    timeOfDay: 'night',
    family: 'respiracion_nocturna',
  },
  {
    key: 'coherencia_cardiaca_5_5',
    name: 'Coherencia cardíaca 5-5 (30 respiraciones)',
    how: 'Inhalar 5 seg, exhalar 5 seg. 30 respiraciones continuas (≈5 min), 2-3 veces al día.',
    benefit: 'Sincroniza HRV, activa vago, baja cortisol, mejora regulación emocional.',
    categories: ['estres', 'ansiedad', 'cardiovascular', 'ritual', 'cognitivo'],
    roots: ['estres_cronico', 'cortisol_elevado_sostenido', 'deficit_neurotransmisores', 'hipertension', 'hrv_baja_cronica'],
    assignRule: 'Estrés crónico, HTA, HRV baja, ansiedad generalizada, burnout.',
    priority: 2,
  },
  {
    key: 'physiological_sigh',
    name: 'Physiological sigh (rescate)',
    how: 'Doble inhalación por nariz (una profunda + una corta para "rellenar") + exhalación larga por boca. Repetir 1-3 veces.',
    benefit: 'Baja arousal simpático en segundos, resetea CO2, calma inmediata sin desregular respiración.',
    categories: ['ansiedad', 'estres', 'ritual', 'cognitivo'],
    roots: ['cortisol_elevado_sostenido', 'adrenalina_nocturna', 'estres_cronico'],
    assignRule: 'Intervención de RESCATE contextual — no diaria. Se activa en picos de ansiedad, transición estrés→foco, antes de decisión difícil.',
    priority: 2,
  },
  {
    key: 'box_breathing_4444',
    name: 'Box breathing 4-4-4-4',
    how: 'Inhalar 4 seg, retener 4 seg, exhalar 4 seg, retener 4 seg. Nivel principiante (día 1).',
    benefit: 'Regula HRV, entrena tolerancia a CO2, calma+foco simultáneos (protocolo Navy SEALs).',
    categories: ['estres', 'ansiedad', 'cognitivo', 'ritual', 'cardiovascular'],
    roots: ['estres_cronico', 'cortisol_elevado_sostenido', 'deficit_neurotransmisores'],
    assignRule: 'Principiante en box breathing (día 1).',
    priority: 2,
    family: 'box_breathing',
  },
  {
    key: 'box_breathing_5555',
    name: 'Box breathing 5-5-5-5',
    how: 'Inhalar 5 seg, retener 5 seg, exhalar 5 seg, retener 5 seg. Nivel intermedio (día 2-3).',
    benefit: 'Mayor tiempo bajo apnea controlada, más entrenamiento vagal.',
    categories: ['estres', 'ansiedad', 'cognitivo', 'ritual', 'cardiovascular'],
    roots: ['estres_cronico', 'cortisol_elevado_sostenido', 'deficit_neurotransmisores'],
    assignRule: 'Progresión desde 4-4-4-4 (día 2-3).',
    priority: 2,
    family: 'box_breathing',
  },
  {
    key: 'box_breathing_6666',
    name: 'Box breathing 6-6-6-6',
    how: 'Inhalar 6 seg, retener 6 seg, exhalar 6 seg, retener 6 seg. Nivel avanzado (día 4+).',
    benefit: 'Adaptación cardio-pulmonar avanzada, foco alto bajo estrés.',
    categories: ['estres', 'ansiedad', 'cognitivo', 'ritual', 'cardiovascular'],
    roots: ['estres_cronico', 'cortisol_elevado_sostenido', 'deficit_neurotransmisores'],
    assignRule: 'Progresión desde 5-5-5-5 (día 4+).',
    priority: 2,
    family: 'box_breathing',
  },
  {
    key: 'wim_hof_basico',
    name: 'Wim Hof Method — básico',
    how: '3 rondas de 30 respiraciones profundas + retención en vacío + inhalación 15 seg reteniendo. ⚠️ NUNCA en agua ni conduciendo.',
    benefit: 'Alcalosis controlada, modula inmunidad, sube adrenalina/dopamina, mejora tolerancia al frío.',
    categories: ['estres', 'inmunologico', 'energia', 'cognitivo', 'ritual'],
    roots: ['deficit_neurotransmisores', 'cortisol_elevado_sostenido', 'estres_cronico'],
    assignRule: '⚠️ NO embarazo, NO epilepsia, NO trastornos cardíacos, NO trastornos psicóticos. Adulto sano curioso en breathwork avanzado.',
    priority: 3,
    family: 'wim_hof',
    requiresClinicalValidation: true,
  },
  {
    key: 'wim_hof_extendido',
    name: 'Wim Hof Method — extendido',
    how: '4 rondas de 40 respiraciones profundas + retenciones más largas. ⚠️ Requiere base previa en WHM básico.',
    benefit: 'Adaptación más profunda al método.',
    categories: ['estres', 'inmunologico', 'energia', 'cognitivo', 'ritual'],
    roots: ['deficit_neurotransmisores', 'cortisol_elevado_sostenido', 'estres_cronico'],
    assignRule: '⚠️ Solo con base sólida en WHM básico. Mismas contraindicaciones.',
    priority: 3,
    family: 'wim_hof',
    requiresClinicalValidation: true,
  },
  {
    key: 'tabla_co2',
    name: 'Tabla CO2 (apnea training)',
    how: '⚠️ Solo en tierra firme. Retenciones de igual duración con descansos decrecientes. Aumenta tolerancia a CO2.',
    benefit: 'Mejora eficiencia respiratoria, adaptación cardio-pulmonar, calma parasimpática.',
    categories: ['cardiovascular', 'estres', 'cognitivo', 'energia'],
    roots: ['estres_cronico', 'cortisol_elevado_sostenido'],
    assignRule: '⚠️ Adulto sano con base de breathwork. Deportes de resistencia, buceo/apnea, foco cognitivo. NO embarazo, NO HTA descompensada, NO epilepsia.',
    priority: 3,
    family: 'apnea_tables',
    requiresClinicalValidation: true,
  },
  {
    key: 'tabla_o2',
    name: 'Tabla O2 (apnea training)',
    how: '⚠️ Solo en tierra firme. Retenciones crecientes con descanso fijo. Aumenta capacidad pulmonar.',
    benefit: 'Aumenta capacidad, adaptación pulmonar avanzada.',
    categories: ['cardiovascular', 'estres', 'cognitivo', 'energia'],
    roots: ['estres_cronico', 'cortisol_elevado_sostenido'],
    assignRule: '⚠️ Adulto sano con base previa en tabla CO2. Mismas contraindicaciones.',
    priority: 3,
    family: 'apnea_tables',
    requiresClinicalValidation: true,
  },
  {
    key: 'hiperventilacion_matutina',
    name: 'Hiperventilación controlada matutina',
    how: '⚠️ Sentado. 30-40 respiraciones rápidas profundas → 15 seg retención en vacío → normal. 1-2 rondas máx en la mañana.',
    benefit: 'Adrenalina + dopamina rápido, alerta cognitiva, activación vagal indirecta.',
    categories: ['energia', 'cognitivo', 'ritual'],
    roots: ['cortisol_matutino_bajo', 'deficit_neurotransmisores', 'ritmo_circadiano_desregulado'],
    assignRule: '⚠️ NO embarazo, epilepsia, arritmias. Adulto sano con energía baja matutina.',
    priority: 3,
    timeOfDay: 'morning',
    requiresClinicalValidation: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // FRÍO / CALOR / TERMORREGULACIÓN
  // ═══════════════════════════════════════════════════════════════════════════

  {
    key: 'ducha_fria_nivel1',
    name: 'Ducha fría — nivel 1 (30-90 seg final)',
    how: 'Termina la ducha con 30-90 segundos de agua fría. Progresión inicial.',
    benefit: 'Activa grasa parda, sube dopamina + norepinefrina, resetea sistema simpático.',
    categories: ['energia', 'estres', 'inmunologico', 'cognitivo', 'cardiovascular'],
    roots: ['deficit_neurotransmisores', 'cortisol_matutino_bajo', 'sedentarismo'],
    assignRule: 'Adulto sano SIN hipertensión descontrolada, arritmias o embarazo. Energía baja o ánimo bajo matutino.',
    priority: 3,
    family: 'ducha_fria',
    timeOfDay: 'morning',
  },
  {
    key: 'ducha_fria_nivel2',
    name: 'Ducha fría — nivel 2 (2-3 min final)',
    how: 'Termina la ducha con 2-3 minutos de agua fría. Progresión intermedia.',
    benefit: 'Mayor exposición al frío, más entrenamiento vagal.',
    categories: ['energia', 'estres', 'inmunologico', 'cognitivo', 'cardiovascular'],
    roots: ['deficit_neurotransmisores', 'cortisol_matutino_bajo', 'sedentarismo'],
    assignRule: 'Ya tolera nivel 1 sistemáticamente.',
    priority: 3,
    family: 'ducha_fria',
    timeOfDay: 'morning',
  },
  {
    key: 'ducha_fria_nivel3',
    name: 'Ducha fría completa',
    how: 'Ducha completamente fría desde el inicio (5-10 min). Nivel avanzado.',
    benefit: 'Máxima exposición al frío en ducha, entrenamiento CNS diario.',
    categories: ['energia', 'estres', 'inmunologico', 'cognitivo', 'cardiovascular'],
    roots: ['deficit_neurotransmisores', 'cortisol_matutino_bajo', 'sedentarismo'],
    assignRule: 'Ya tolera nivel 2. Adulto sano sin contraindicaciones cardiovasculares.',
    priority: 3,
    family: 'ducha_fria',
    timeOfDay: 'morning',
  },
  {
    key: 'sauna_infrarrojo',
    name: 'Sauna infrarrojo lejano',
    how: '30-45 min a 45-60°C, 3-5×/semana. Hidratar antes y después.',
    benefit: 'Heat shock proteins, mayor penetración térmica, más tolerable que sauna tradicional.',
    categories: ['cardiovascular', 'inmunologico', 'inflamacion', 'ritual', 'piel', 'energia'],
    roots: ['inflamacion_silenciosa', 'toxicidad_ambiental', 'sedentarismo', 'cortisol_elevado_sostenido'],
    assignRule: 'Adulto sin arritmias descompensadas, embarazo, HTA descontrolada. Flag P1 si inflamación crónica o burnout.',
    priority: 2,
    family: 'sauna',
  },
  {
    key: 'sauna_finlandesa',
    name: 'Sauna finlandesa (seca)',
    how: '15-20 min a 80-90°C, 3-5×/semana. Hidratar antes y después.',
    benefit: 'Máximo heat shock protein, cardio-adaptación intensa (Finnish mortality studies).',
    categories: ['cardiovascular', 'inmunologico', 'inflamacion', 'ritual', 'energia'],
    roots: ['inflamacion_silenciosa', 'toxicidad_ambiental', 'sedentarismo', 'cortisol_elevado_sostenido'],
    assignRule: 'Adulto sin contraindicaciones cardiovasculares. Base previa en sauna.',
    priority: 2,
    family: 'sauna',
  },
  {
    key: 'sauna_vapor',
    name: 'Sauna de vapor',
    how: '15-20 min a 40-45°C, 3-5×/semana.',
    benefit: 'Foco en piel + respiratorio, menos estrés cardiovascular.',
    categories: ['piel', 'inmunologico', 'inflamacion', 'ritual'],
    roots: ['inflamacion_silenciosa', 'toxicidad_ambiental'],
    assignRule: 'Adulto sin embarazo. Ideal si piel o vía respiratoria son foco.',
    priority: 2,
    family: 'sauna',
  },
  {
    key: 'bano_frio_desinflamacion',
    name: 'Baño frío 10-15°C (desinflamación)',
    how: 'Inmersión a 10-15°C, 2-5 min, 2-4×/semana. Idealmente mañana o post-entrenamiento.',
    benefit: 'Activa grasa parda, reduce inflamación post-ejercicio, mejora recuperación, resetea vago.',
    categories: ['inflamacion', 'inmunologico', 'metabolismo', 'cardiovascular'],
    roots: ['inflamacion_silenciosa', 'sedentarismo', 'ritmo_circadiano_desregulado'],
    assignRule: 'Adulto sano SIN embarazo, HTA descontrolada, arritmias, Raynaud severo. Flag P1 si inflamación crónica o dolor articular.',
    priority: 2,
    family: 'bano_frio',
  },
  {
    key: 'cold_plunge_cns',
    name: 'Cold plunge 2-6°C (CNS training)',
    how: 'Inmersión a 2-6°C, 30 seg-3 min máx, 2-3×/semana. Requiere base previa de 10-15°C.',
    benefit: 'Entrenamiento CNS bajo estrés controlado, adrenalina/dopamina/norepinefrina 5×, resiliencia psicológica.',
    categories: ['energia', 'estres', 'cognitivo'],
    roots: ['deficit_neurotransmisores', 'cortisol_matutino_bajo', 'cortisol_elevado_sostenido'],
    assignRule: 'Adulto sano avanzado (tolera 10-15°C). Flag P1 si necesita entrenamiento mental / resiliencia.',
    priority: 3,
    family: 'bano_frio',
  },
  {
    key: 'bano_caliente_vespertino',
    name: 'Baño caliente vespertino',
    how: '20-40 min a 38-42°C, 1-2h antes de dormir. Opcional sales de Epsom.',
    benefit: 'Vasodilata, ayuda a caída de temperatura corporal para el sueño, relaja músculo.',
    categories: ['sueno', 'cardiovascular', 'ritual', 'estres'],
    roots: ['cortisol_elevado_sostenido', 'deficit_sueno_profundo', 'estres_cronico', 'adrenalina_nocturna'],
    assignRule: 'Insomnio de conciliación, estrés vespertino, tensión muscular, post-entrenamiento intenso.',
    priority: 2,
    timeOfDay: 'evening',
  },
  {
    key: 'terapia_contraste',
    name: 'Terapia de contraste (caliente/frío)',
    how: 'Alternar 3 min caliente + 30-60 seg frío. 3-5 ciclos. Terminar en frío.',
    benefit: '"Ejercicio vascular", mejora HRV, drena linfa, entrena vago.',
    categories: ['cardiovascular', 'inmunologico', 'energia', 'estres'],
    roots: ['sedentarismo', 'cortisol_elevado_sostenido', 'inflamacion_silenciosa'],
    assignRule: 'Adulto sano avanzado en frío + calor por separado.',
    priority: 3,
  },
  {
    key: 'dive_reflex_cara_hielo',
    name: 'Cara en agua con hielo (dive reflex)',
    how: 'Recipiente con agua + hielo, sumergir cara (incluida frente) 15-30 seg, respirar antes de sumergir.',
    benefit: 'Activa dive reflex (bradicardia + vasoconstricción periférica), reset vagal potente, corta ataques de pánico, energizante matutino.',
    categories: ['ansiedad', 'estres', 'cardiovascular', 'energia', 'cognitivo'],
    roots: ['adrenalina_nocturna', 'estres_cronico', 'cortisol_elevado_sostenido', 'cortisol_matutino_bajo', 'hrv_baja_cronica'],
    assignRule: 'Ataques de pánico, sobre-arousal, pico ansiedad, bajo cortisol matutino (en la mañana), HRV crónicamente baja. ⚠️ NO si arritmias.',
    priority: 2,
    requiresClinicalValidation: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LUZ Y VISIÓN
  // ═══════════════════════════════════════════════════════════════════════════

  {
    key: 'lentes_amarillos',
    name: 'Lentes amarillos (filtro leve)',
    how: 'Lentes con filtro amarillo todo el día mientras trabajas en pantalla.',
    benefit: 'Bloquea luz azul artificial suave, protege durante deep work prolongado.',
    categories: ['sueno', 'circadiano', 'cognitivo'],
    roots: ['sobreexposicion_luz_azul', 'ritmo_circadiano_desregulado'],
    assignRule: 'Trabajo intensivo en pantalla >4h/día.',
    priority: 2,
    family: 'lentes_azul',
  },
  {
    key: 'lentes_ambar',
    name: 'Lentes ámbar (filtro moderado)',
    how: 'Lentes ámbar vespertinos después de las 18h.',
    benefit: 'Bloquea luz azul moderada, protege cascada melatonina de la tarde.',
    categories: ['sueno', 'circadiano'],
    roots: ['sobreexposicion_luz_azul', 'ritmo_circadiano_desregulado', 'deficit_sueno_profundo'],
    assignRule: 'Exposición vespertina forzada a pantallas, turnista.',
    priority: 2,
    family: 'lentes_azul',
    timeOfDay: 'evening',
  },
  {
    key: 'lentes_rojos',
    name: 'Lentes rojos (filtro máximo)',
    how: 'Lentes rojos 90 min antes de dormir. Corta ~99% de la luz azul.',
    benefit: 'Máxima protección de melatonina en las horas críticas pre-sueño.',
    categories: ['sueno', 'circadiano'],
    roots: ['sobreexposicion_luz_azul', 'ritmo_circadiano_desregulado', 'deficit_sueno_profundo'],
    assignRule: 'Insomnio, exposición nocturna forzada, turnista.',
    priority: 2,
    family: 'lentes_azul',
    timeOfDay: 'night',
  },
  {
    key: 'luz_roja_ojos',
    name: 'Luz roja / NIR en los ojos',
    how: '⚠️ Solo con dispositivo calibrado. 30-60 seg de luz roja 660nm en ojos cerrados.',
    benefit: 'Fotobiomodulación mitocondrial retinal. Estudios sugieren mejora agudeza visual >40 años.',
    categories: ['cognitivo', 'piel', 'energia'],
    roots: ['deficit_exposicion_solar', 'sobreexposicion_luz_azul'],
    assignRule: '⚠️ Requiere dispositivo apropiado (no LED común). Adulto sin patologías oculares diagnosticadas.',
    priority: 3,
    requiresClinicalValidation: true,
  },
  {
    key: 'panel_rojo_recovery',
    name: 'Panel luz roja + NIR (recovery cuerpo)',
    how: 'Panel calibrado 660nm + 850nm NIR, 10-20 min sobre piel expuesta, distancia ~15-30cm, 4-5×/sem.',
    benefit: 'Fotobiomodulación mitocondrial, reduce inflamación local, mejora recovery muscular.',
    categories: ['inflamacion', 'movimiento', 'hormonal', 'cognitivo', 'piel'],
    roots: ['inflamacion_silenciosa', 'deficit_exposicion_solar'],
    assignRule: 'Deportistas con dolor crónico articular, inflamación, post-lesión.',
    priority: 3,
    family: 'panel_luz_roja',
  },
  {
    key: 'panel_rojo_cara',
    name: 'Panel luz roja para cara (piel)',
    how: 'Panel 660nm + 850nm sobre cara, 10-15 min, 4-5×/sem.',
    benefit: 'Colágeno + elastina, rejuvenecimiento piel.',
    categories: ['piel', 'inflamacion'],
    roots: ['inflamacion_silenciosa', 'deficit_exposicion_solar'],
    assignRule: 'Piel envejecida, textura irregular, líneas finas.',
    priority: 3,
    family: 'panel_luz_roja',
  },
  {
    key: 'ejercicio_ocular_near_far',
    name: 'Ejercicio ocular cerca/lejos',
    how: 'Cada 20 min de pantalla, mira 20 seg a un objeto lejano (≥6m). Alternar 5-10 ciclos.',
    benefit: 'Preserva capacidad de acomodación, reduce fatiga ocular, previene miopía adquirida.',
    categories: ['cognitivo', 'ritual'],
    roots: ['sobreexposicion_luz_azul'],
    assignRule: 'Trabajo pantalla >4h/día, miopía, fatiga ocular.',
    priority: 2,
  },
  {
    key: 'parpadeo_consciente',
    name: 'Parpadeo consciente en pantalla',
    how: 'Parpadeos completos conscientes 5×/min mientras usas pantalla + hidratar ojos.',
    benefit: 'Previene ojo seco por sub-parpadeo, lubrica córnea.',
    categories: ['ritual', 'cognitivo'],
    roots: ['sobreexposicion_luz_azul'],
    assignRule: 'Trabajo pantalla >4h, ojo seco, ojo rojo vespertino.',
    priority: 3,
  },
  {
    key: 'compresa_fria_ojos',
    name: 'Compresa fría en ojos',
    how: '5-10 min compresa fría (gel pack) sobre ojos cerrados, después de trabajo pantalla o al despertar hinchado.',
    benefit: 'Vasoconstricción, reduce inflamación periorbital, alivia fatiga ocular.',
    categories: ['piel', 'cognitivo', 'ritual'],
    roots: ['inflamacion_silenciosa', 'sobreexposicion_luz_azul'],
    assignRule: 'Fatiga ocular, hinchazón matutina, alergias, migraña ocular.',
    priority: 3,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MOVIMIENTO + FUERZA
  // ═══════════════════════════════════════════════════════════════════════════

  {
    key: 'pausas_activas_60min',
    name: 'Pausas activas cada 60 min',
    how: 'Cada hora: levántate, 2 min de estiramiento cervical + puntitas + respiración diafragmática 5 ciclos.',
    benefit: 'Rompe estasis linfática, resetea foco cognitivo, previene tensión postural.',
    categories: ['movimiento', 'ritual', 'cognitivo', 'cardiovascular'],
    roots: ['sedentarismo', 'sarcopenia', 'ritmo_circadiano_desregulado', 'estres_cronico'],
    assignRule: 'Trabajo sentado >6h/día, dolor lumbar/cervical, caídas de foco vespertino.',
    priority: 2,
    family: 'pausas_activas',
  },
  {
    key: 'pausas_activas_90min',
    name: 'Pausas activas cada 90 min',
    how: 'Cada 90 min: levántate, 2 min de estiramiento + respiración.',
    benefit: 'Menor interrupción que 60 min. Para deep work sostenido.',
    categories: ['movimiento', 'ritual', 'cognitivo', 'cardiovascular'],
    roots: ['sedentarismo', 'sarcopenia', 'estres_cronico'],
    assignRule: 'Deep work sostenido con menor tolerancia a interrupción.',
    priority: 2,
    family: 'pausas_activas',
  },
  {
    key: 'standing_desk',
    name: 'Escritorio elevado (standing desk)',
    how: 'Alterna cada 45-60 min entre sentado y de pie durante el día laboral.',
    benefit: 'Reduce mortalidad asociada a sedentarismo, mejora glucosa postprandial, activa cadena posterior.',
    categories: ['movimiento', 'metabolismo', 'cardiovascular', 'ritual'],
    roots: ['sedentarismo', 'sarcopenia', 'hiperinsulinemia'],
    assignRule: 'Trabajo sentado >6h/día, dolor lumbar, glucosa postprandial elevada.',
    priority: 2,
  },
  {
    key: 'meta_pasos_8k',
    name: 'Meta 8,000 pasos diarios',
    how: 'Distribuye 8,000 pasos al día. Contar con reloj/teléfono.',
    benefit: 'Reducción de mortalidad significativa, base de composición corporal.',
    categories: ['movimiento', 'cardiovascular', 'metabolismo', 'ritual'],
    roots: ['sedentarismo', 'sarcopenia', 'hiperinsulinemia'],
    assignRule: 'Sedentario que empieza a moverse.',
    priority: 2,
    family: 'meta_pasos',
  },
  {
    key: 'meta_pasos_10k',
    name: 'Meta 10,000 pasos diarios',
    how: 'Distribuye 10,000 pasos al día. Óptimo cardiovascular.',
    benefit: 'Ganancia cardiovascular óptima. Base de longevidad.',
    categories: ['movimiento', 'cardiovascular', 'metabolismo', 'ritual'],
    roots: ['sedentarismo', 'sarcopenia', 'hiperinsulinemia'],
    assignRule: 'Adulto activo buscando longevidad cardiovascular.',
    priority: 1,
    family: 'meta_pasos',
  },
  {
    key: 'meta_pasos_12k',
    name: 'Meta 12,000+ pasos diarios',
    how: 'Distribuye 12,000+ pasos al día. Nivel deportista.',
    benefit: 'Composición corporal + rendimiento deportivo.',
    categories: ['movimiento', 'cardiovascular', 'metabolismo', 'ritual'],
    roots: ['sedentarismo', 'sarcopenia'],
    assignRule: 'Deportistas o composición corporal como objetivo.',
    priority: 2,
    family: 'meta_pasos',
  },
  {
    key: 'death_hang',
    name: 'Death hang (colgar 30-90 seg)',
    how: 'Colgar de una barra con brazos estirados, hombros relajados, 30-90 seg. 2-3 sets, 3-5×/sem.',
    benefit: 'Descompresión columna, movilidad de hombro, grip strength (predictor mortalidad), abre cadena posterior.',
    categories: ['movimiento', 'cardiovascular', 'hormonal', 'ritual'],
    roots: ['sedentarismo', 'sarcopenia'],
    assignRule: 'Adulto sano, rigidez de hombro/cuello, dolor lumbar por decúbito.',
    priority: 2,
  },
  {
    key: 'farmers_walk',
    name: "Caminata del granjero (Farmer's walk)",
    how: 'Camina 20-40m cargando peso significativo en cada mano. 3-5 sets.',
    benefit: 'Grip + core + posture. Marker de longevidad y condicionamiento anaeróbico.',
    categories: ['movimiento', 'cardiovascular', 'hormonal', 'metabolismo'],
    roots: ['sarcopenia', 'sedentarismo', 'baja_testosterona'],
    assignRule: 'Adulto con base de fuerza, sarcopenia, declive de fuerza con edad.',
    priority: 2,
  },
  {
    key: 'jawzercise',
    name: 'Jawzercise / mewing (ejercicio mandibular)',
    how: 'Fuerza masticatoria con chicle duro, alimentos duros, ejercicios de mewing. Herramienta comprable: Jawzrsize / Jawline Trainer, 5-10 min/día.',
    benefit: 'Estructura maxilo-facial, apnea del sueño (evidencia limitada), fuerza masticatoria.',
    categories: ['ritual', 'sueno'],
    roots: ['deficit_sueno_profundo'],
    assignRule: 'Apnea leve, retrognatia, debilidad masticatoria.',
    priority: 3,
    requiresClinicalValidation: true,
  },
  {
    key: 'separadores_dedos_pies',
    name: 'Separadores de dedos de los pies',
    how: 'Separadores de silicona 15-30 min/día (con calcetín) o al dormir. Progresar tolerancia.',
    benefit: 'Corrige compresión digital por calzado moderno, mejora arco, propriocepción, previene juanetes.',
    categories: ['movimiento', 'ritual'],
    roots: [],
    assignRule: 'Calzado estrecho, juanetes incipientes, dolor plantar.',
    priority: 3,
  },
  {
    key: 'zona_2_aerobica',
    name: 'Zona 2 aeróbica 2-3×/semana',
    how: '30-45 min de ejercicio aeróbico a intensidad "zona 2" (60-70% FC máx). Trote suave, bici, remo.',
    benefit: 'Densidad mitocondrial, base metabólica aeróbica, oxidación de grasas, longevidad cardiovascular (Attia).',
    categories: ['cardiovascular', 'metabolismo', 'energia', 'movimiento'],
    roots: ['hiperinsulinemia', 'sedentarismo', 'baja_testosterona', 'sarcopenia'],
    assignRule: 'Universal recomendado adulto ≥35 años. Flag P1 si sedentarismo.',
    priority: 1,
    evidenceLevel: 'N2',
  },
  {
    key: 'vo2max_training',
    name: 'VO2max training zona 5 (⚠️ solo entrenados)',
    how: '4×(4 min zona 5 al 90-95% FC máx + 3 min recuperación). ⚠️ CALENTAMIENTO OBLIGATORIO 10-15 min zona 2 antes.',
    benefit: 'VO2max = predictor #1 de mortalidad (Attia). Mejora capacidad mitocondrial máxima.',
    categories: ['cardiovascular', 'metabolismo', 'hormonal', 'energia'],
    roots: ['sedentarismo', 'baja_testosterona', 'sarcopenia'],
    assignRule: '⚠️ Solo adulto con entrenamiento aeróbico consistente ≥3 meses. Sin patología cardiovascular. NUNCA sin calentamiento previo 10-15 min.',
    priority: 2,
    scientificInfo: '99% de las personas se lesionan haciendo sprints de golpe sin base previa.',
  },
  {
    key: 'levantamiento_compuesto',
    name: 'Levantamiento pesado compuesto',
    how: 'Sentadilla + peso muerto + press + jalón + remo, 3-5 sets × 5-8 reps con progresión de carga, 2-3×/semana.',
    benefit: 'Combate sarcopenia (predictor mortalidad), sube testosterona/GH, densidad ósea, control glucémico.',
    categories: ['movimiento', 'hormonal', 'metabolismo', 'cardiovascular'],
    roots: ['sarcopenia', 'baja_testosterona', 'hipertension', 'hiperinsulinemia', 'sedentarismo'],
    assignRule: 'Universal recomendado adulto ≥30. Enrique: peso muerto es el favorito clínico.',
    priority: 1,
    evidenceLevel: 'N1',
  },
  {
    key: 'ejercicio_ayuno_cardio',
    name: 'Cardio zona 2 en ayuno',
    how: '30-45 min de cardio zona 2 en ayuno de 16h+. Desayunar rico en proteína al terminar.',
    benefit: 'Mejora sensibilidad a insulina, oxidación de grasas, mtDNA repair.',
    categories: ['metabolismo', 'movimiento', 'hormonal'],
    roots: ['hiperinsulinemia', 'resistencia_insulina'],
    assignRule: 'Adulto con resistencia insulina, sin desórdenes alimentación, sin baja de rendimiento excesiva.',
    priority: 2,
    family: 'ejercicio_ayuno',
  },
  {
    key: 'ejercicio_ayuno_fuerza',
    name: 'Fuerza en ayuno (⚠️ tolera)',
    how: 'Sesión de fuerza en ayuno de 16h+. ⚠️ Solo si tolera, no PR.',
    benefit: 'Autofagia muscular controlada, sensibilidad a insulina.',
    categories: ['metabolismo', 'movimiento', 'hormonal'],
    roots: ['hiperinsulinemia', 'resistencia_insulina', 'sarcopenia'],
    assignRule: 'Adulto avanzado que ya tolera cardio en ayuno. Sin PR, sin desórdenes.',
    priority: 3,
    family: 'ejercicio_ayuno',
    requiresClinicalValidation: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // NUTRICIÓN
  // ═══════════════════════════════════════════════════════════════════════════

  {
    key: 'eliminar_aceites_vegetales',
    name: 'Eliminar aceites vegetales industriales',
    how: 'Retira soya, canola, girasol refinado, maíz refinado, "aceite vegetal", margarinas. Sustituir por oliva EV, aguacate, coco, mantequilla clarificada, manteca pastoreada.',
    benefit: 'Reduce carga omega-6 pro-inflamatoria, mejora ratio omega-3/6, baja inflamación silenciosa.',
    categories: ['inflamacion', 'metabolismo', 'cardiovascular', 'nutricion'],
    roots: ['inflamacion_silenciosa', 'sobrecarga_procesados', 'sobrecarga_hepatica'],
    assignRule: 'Universal recomendado (énfasis Enrique). Flag P1 si PCR-us elevada, dolor articular crónico, dieta alta en procesados.',
    priority: 1,
    evidenceLevel: 'N2',
  },
  {
    key: 'sardinas_pescados_grasos',
    name: 'Sardinas / pescados grasos 2-3×/semana',
    how: 'Sardinas, salmón salvaje, arenque, macarela — 100-150g, 2-3 porciones semanales.',
    benefit: 'Omega-3 EPA/DHA dietético (mejor que cápsula), vitamina D, proteína alta calidad, colina.',
    categories: ['inflamacion', 'cardiovascular', 'cognitivo', 'nutricion'],
    roots: ['inflamacion_silenciosa', 'deficit_neurotransmisores'],
    assignRule: 'Universal recomendado. Flag P1 si dieta baja en pescado, inflamación, deficiencia detectada.',
    priority: 2,
    family: 'sardinas',
  },
  {
    key: 'protocolo_ayuno_sardinas',
    name: 'Protocolo Ayuno de Sardinas',
    how: '⏳ Detalles del protocolo pendientes — Enrique tiene el detalle y lo pasa a Cowork para completar.',
    benefit: 'Protocolo específico que Mariana + Enrique tienen documentado. Combina ayuno con sardinas.',
    categories: ['inflamacion', 'metabolismo', 'nutricion'],
    roots: ['inflamacion_silenciosa', 'hiperinsulinemia'],
    assignRule: 'Pendiente completar. Requiere spec de Enrique.',
    priority: 2,
    family: 'sardinas',
    scientificInfo: 'Placeholder — Enrique aporta detalles del protocolo.',
    requiresClinicalValidation: true,
  },
  {
    key: 'visceras_higado',
    name: 'Vísceras (hígado) 1×/semana',
    how: '60-100g de hígado de res/pollo pastoreado, cocinado como paté o entero.',
    benefit: 'Nutrient density máximo (B12 real, hierro heme, cobre, vit A retinol, colina).',
    categories: ['nutricion', 'energia', 'cognitivo', 'hormonal'],
    roots: ['deficit_neurotransmisores'],
    assignRule: 'Déficit de nutrientes por dieta, anemia, vegetarianismo transitional, embarazo (⚠️ dosis).',
    priority: 3,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MENTE / COGNITIVO / MEDITACIÓN
  // ═══════════════════════════════════════════════════════════════════════════

  {
    key: 'journal_am',
    name: 'Journal AM (3 min al despertar)',
    how: '3 min escribiendo a mano al despertar: 1 cosa que agradezco + 1 sensación en el cuerpo + 1 intención del día.',
    benefit: 'Ancla presencia, activa red default de manera saludable, reduce rumiación diurna.',
    categories: ['ritual', 'cognitivo', 'ansiedad', 'estres'],
    roots: ['estres_cronico', 'deficit_neurotransmisores', 'cortisol_elevado_sostenido'],
    assignRule: 'Ansiedad generalizada, rumiación, falta de foco, burnout, alta reactividad emocional. Intención + presencia.',
    priority: 3,
    family: 'journal',
    timeOfDay: 'morning',
  },
  {
    key: 'journal_pm',
    name: 'Journal PM (3 min antes de dormir)',
    how: '3 min escribiendo a mano antes de dormir: 1 win del día + 1 lección + 1 cosa que suelto.',
    benefit: 'Cierre + integración del día, procesamiento emocional, mejora sueño por descarga mental.',
    categories: ['ritual', 'cognitivo', 'sueno', 'ansiedad'],
    roots: ['estres_cronico', 'adrenalina_nocturna', 'cortisol_elevado_sostenido'],
    assignRule: 'Rumiación nocturna, insomnio, alta carga emocional del día, burnout.',
    priority: 3,
    family: 'journal',
    timeOfDay: 'night',
  },
  {
    key: 'nsdr_10min',
    name: 'NSDR 10 min (micro-descanso)',
    how: 'Grabación guiada de NSDR 10 min, acostado, escaneo corporal + respiración.',
    benefit: 'Recupera fatiga como microsueño sin dormir, baja cortisol, restaura dopamina (Huberman).',
    categories: ['estres', 'ansiedad', 'cognitivo', 'ritual', 'sueno'],
    roots: ['estres_cronico', 'cortisol_elevado_sostenido', 'deficit_neurotransmisores', 'deficit_sueno_profundo'],
    assignRule: 'Post-comida crash, jet-lag, burnout, siesta imposible.',
    priority: 2,
    family: 'nsdr_yoga_nidra',
  },
  {
    key: 'yoga_nidra_30min',
    name: 'Yoga Nidra 20-30 min (restaurativo)',
    how: 'Grabación guiada de Yoga Nidra 20-30 min, acostado. Meditativo profundo.',
    benefit: 'Restauración profunda, baja cortisol sostenidamente, mejora arquitectura de sueño.',
    categories: ['estres', 'ansiedad', 'cognitivo', 'ritual', 'sueno'],
    roots: ['estres_cronico', 'cortisol_elevado_sostenido', 'deficit_neurotransmisores', 'deficit_sueno_profundo'],
    assignRule: 'Burnout profundo, insomnio crónico, ansiedad sostenida.',
    priority: 2,
    family: 'nsdr_yoga_nidra',
  },
  {
    key: 'binaurales_delta',
    name: 'Frecuencias binaurales delta (pre-sueño)',
    how: 'Auriculares + frecuencia delta 2Hz, 15-30 min antes de dormir.',
    benefit: 'Entrainment cerebral hacia estado delta (sueño profundo), facilita conciliación.',
    categories: ['sueno', 'cognitivo', 'ritual', 'ansiedad'],
    roots: ['deficit_sueno_profundo', 'adrenalina_nocturna', 'estres_cronico'],
    assignRule: 'Insomnio de conciliación, transición al sueño difícil.',
    priority: 3,
    family: 'binaurales',
    timeOfDay: 'night',
  },
  {
    key: 'binaurales_theta',
    name: 'Frecuencias binaurales theta (meditación)',
    how: 'Auriculares + frecuencia theta 6Hz, 15-30 min durante meditación.',
    benefit: 'Facilita estados meditativos profundos, creatividad, insight.',
    categories: ['estres', 'cognitivo', 'ritual'],
    roots: ['estres_cronico', 'deficit_neurotransmisores'],
    assignRule: 'Práctica meditativa que requiere profundidad.',
    priority: 3,
    family: 'binaurales',
  },
  {
    key: 'binaurales_alpha',
    name: 'Frecuencias binaurales alpha (relax)',
    how: 'Auriculares + frecuencia alpha 10Hz, 15-30 min para relax + creatividad.',
    benefit: 'Estado alfa relajado con presencia, ideal para transición o creatividad.',
    categories: ['estres', 'ansiedad', 'cognitivo', 'ritual'],
    roots: ['estres_cronico', 'deficit_neurotransmisores'],
    assignRule: 'Transición estrés → foco, creatividad, relax activo.',
    priority: 3,
    family: 'binaurales',
  },
  {
    key: 'binaurales_beta',
    name: 'Frecuencias binaurales beta (deep work)',
    how: 'Auriculares + frecuencia beta 20Hz, 15-30 min durante deep work.',
    benefit: 'Foco intenso, alerta cognitiva, resistencia al distractor.',
    categories: ['cognitivo', 'ritual', 'energia'],
    roots: ['deficit_neurotransmisores'],
    assignRule: 'Deep work demandante, foco cognitivo.',
    priority: 3,
    family: 'binaurales',
  },
  {
    key: 'n_back_challenge',
    name: 'N-Back Challenge (working memory)',
    how: 'Ejercicio de working memory dual: recordar simultáneamente posición espacial + auditiva de N pasos atrás. Progresión INFINITA en N. 15-20 min/día, 5-6×/sem.',
    benefit: 'Único ejercicio con evidencia de mejora working memory + IQ fluido en adultos (Jaeggi 2008), previene declive cognitivo.',
    categories: ['cognitivo', 'ritual'],
    roots: ['deficit_neurotransmisores'],
    assignRule: 'Adulto con declive cognitivo autoreportado, brain fog, trabajo cognitivo demandante, biohacker curioso. ⚠️ FEATURE APP GRANDE — Cowork investiga referencias antes de spec técnica.',
    priority: 3,
    evidenceLevel: 'N2',
  },
  {
    key: 'silencio_30min',
    name: 'Silencio 30 min/día',
    how: '30 min al día sin música, podcasts, TV, redes. Puede ser al caminar, cocinar o sentarse.',
    benefit: 'Baja carga cognitiva, permite consolidación memoria default mode, reduce cortisol.',
    categories: ['estres', 'cognitivo', 'ansiedad', 'ritual'],
    roots: ['cortisol_elevado_sostenido', 'estres_cronico', 'deficit_neurotransmisores'],
    assignRule: 'Universal — especialmente burnout, sobrecarga info, rumiación.',
    priority: 2,
  },
  {
    key: 'green_time_30min',
    name: 'Green time (naturaleza) 30 min/día',
    how: '30 min al día en espacio verde: parque, bosque, jardín, playa. Idealmente sin celular.',
    benefit: 'Reduce cortisol, mejora HRV, attention restoration, exposición a microbioma diverso.',
    categories: ['estres', 'ansiedad', 'cognitivo', 'inmunologico', 'ritual'],
    roots: ['estres_cronico', 'cortisol_elevado_sostenido', 'disbiosis', 'deficit_exposicion_solar'],
    assignRule: 'Universal — flag P1 si burnout, ambiente urbano intenso, deficiencia sensorial.',
    priority: 2,
  },
  {
    key: 'digital_minimalism_1dia_semana',
    name: 'Digital minimalism 1 día/semana',
    how: 'Un día a la semana sin redes sociales, sin news, uso de celular limitado a llamadas/mensajes esenciales.',
    benefit: 'Restaura dopamina baseline, mejora atención, reduce comparación social, protege sueño.',
    categories: ['cognitivo', 'estres', 'ansiedad', 'ritual', 'sueno'],
    roots: ['deficit_neurotransmisores', 'estres_cronico', 'sobreexposicion_luz_azul'],
    assignRule: 'Adulto con hi-usage de redes (>2h/día), ansiedad, burnout, falta de foco.',
    priority: 2,
  },
];

// ── Índices de acceso ────────────────────────────────────────────────────────

export const INTERVENTION_BY_KEY: Record<string, Intervention> =
  Object.fromEntries(INTERVENTIONS_CATALOG.map(i => [i.key, i]));

/** Universales garantizados (fallback cuando el DX no arroja raíces o el catálogo es chico). */
export const UNIVERSAL_INTERVENTIONS: Intervention[] =
  INTERVENTIONS_CATALOG.filter(i => i.isUniversal);

/** Intervenciones que requieren validación clínica adicional antes de producción. */
export const CLINICAL_VALIDATION_PENDING: Intervention[] =
  INTERVENTIONS_CATALOG.filter(i => i.requiresClinicalValidation);
