-- NOTA DE VERSION (5 de septiembre de 2026): estas tres migraciones se registraron en
-- produccion con version timestamp (20260904203502, 20260905151702, 20260906040335).
-- El CLI 2.102 ordena lo local por nombre de archivo y lo remoto por version, y con
-- formatos mezclados (numerico corto + timestamp) desalinea la lista y aborta db push.
-- Se renumeraron a 268, 269 y 270 (numeros libres, mismo largo que sus vecinas) y el
-- ledger remoto se reparo con `supabase migration repair` (reverted las timestamp,
-- applied 268 269 270). El contenido no cambia; nada de esto se ejecuta en produccion.
-- 269_levantamiento_dx_v2_entrevista_completa.sql (antes 20260905151702_levantamiento_dx_v2_entrevista_completa.sql)
--
-- Version registrada en supabase_migrations.schema_migrations de produccion el
-- 5 de septiembre de 2026 (nota del ledger: "+68 columnas: historia clinica
-- ampliada, digestion, boca/piel, entrenamiento, sueno ampliado, cronotipo,
-- vitalidad, contexto, mujer"), aplicada con execute_sql desde otra sesion sin
-- archivo en el repo.
--
-- Contenido incluido en la reconstruccion de 20260904203502; version
-- registrada para cuadrar el ledger. Sin statements a proposito.
